"""dbt YAML projection emission from validated ``modelable.plan/v1`` documents."""

from __future__ import annotations

from pathlib import Path
from typing import cast

import yaml

from modelable.emitters.base import EmittedArtifact, compute_content_hash
from modelable.planner.protocol import PlanDocument, validate_plan


def emit_dbt_projection_plan(
    plan: PlanDocument,
    out_dir: Path,
    *,
    domain_owner: str | None = None,
    domain_contact: str | None = None,
    domain_description: str | None = None,
) -> EmittedArtifact:
    """Build one dbt schema fragment from a validated plan document."""
    document = validate_plan(plan)
    domain = _string(document, "domain")
    projection = _string(document, "projection")
    version = _integer(document, "version")
    source = _mapping(document, "source")
    source_ref = f"{_string(source, 'model')}@{_version_label(_mapping(source, 'version'))}"

    meta: dict[str, object] = {
        "modelable_domain": domain,
        "modelable_name": projection,
        "modelable_kind": "projection",
        "modelable_version": version,
        "modelable_source": source_ref,
    }
    if domain_owner:
        meta["modelable_owner"] = domain_owner
    if domain_contact:
        meta["modelable_contact"] = domain_contact
    where = document.get("where")
    if where:
        meta["modelable_where"] = where
    group_by = _list(document, "group_by")
    if group_by:
        meta["modelable_group_by"] = ", ".join(_string_value(item, "group_by") for item in group_by)

    model_entry: dict[str, object] = {
        "name": projection,
        "latest_version": version,
        "meta": meta,
        "versions": [{"v": version, "columns": [_column(field, domain_owner) for field in _list(document, "fields")]}],
    }
    if domain_description:
        model_entry["description"] = domain_description

    doc = {"version": 2, "models": [model_entry]}
    content = f"# @generated by Modelable\n{yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)}"
    artifact_id = f"{domain}.{projection}.v{version}"
    return EmittedArtifact(
        target="dbt-yaml",
        ref=f"{domain}.{projection}@{version}",
        artifact_id=artifact_id,
        path=out_dir / f"{artifact_id}.yml",
        content=content,
        content_hash=compute_content_hash(content),
    )


def _column(value: object, domain_owner: str | None) -> dict[str, object]:
    field = _mapping_value(value, "field")
    kind = _string(field, "kind")
    field_type = field.get("type")
    column: dict[str, object] = {
        "name": _string(field, "name"),
        "data_type": "text" if kind != "direct" else _type_to_dbt(field_type),
    }
    column_meta: dict[str, object] = {}
    lineage = _list(field, "lineage")
    if lineage:
        column_meta["modelable_lineage"] = lineage
    if _bool(field, "pii"):
        column_meta["modelable_pii"] = True
    classification = field.get("classification")
    if isinstance(classification, str) and classification:
        column_meta["modelable_classification"] = classification
    if domain_owner:
        column_meta["modelable_owner"] = domain_owner
    if column_meta:
        column["meta"] = column_meta
    return column


def _type_to_dbt(value: object) -> str:
    if not isinstance(value, dict):
        return "text"
    kind = value.get("kind")
    if kind == "string":
        return "text"
    if kind == "int" or kind in {"i8", "i16", "i32", "i64", "i128", "u8", "u16", "u32", "u64", "u128"}:
        return "integer"
    if kind == "float":
        return "float"
    if kind == "bool":
        return "boolean"
    if kind in {"date", "time", "timestamp"}:
        return cast(str, kind)
    if kind == "uuid":
        return "uuid"
    if kind == "binary":
        return "binary"
    if kind in {"duration", "json", "fixed_binary", "map", "ref", "enum", "enum_ref", "named", "object", "union"}:
        return "text"
    if kind == "decimal":
        return f"numeric({value.get('precision')}, {value.get('scale')})"
    if kind == "array":
        return f"{_type_to_dbt(value.get('item'))}[]"
    return "text"


def _version_label(version: dict[str, object]) -> str:
    kind = _string(version, "kind")
    if kind in {"exact", "pinned"}:
        label = str(_integer(version, "version"))
        if kind == "pinned":
            label += f"#{_string(version, 'contentHash')}"
        return label
    if kind == "range":
        return f">={_integer(version, 'minInclusive')}<{_integer(version, 'maxExclusive')}"
    return f">={_integer(version, 'minInclusive')}"


def _mapping(mapping: dict[str, object], name: str) -> dict[str, object]:
    return _mapping_value(mapping.get(name), name)


def _mapping_value(value: object, name: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"plan {name} must be an object")
    return value


def _list(mapping: dict[str, object], name: str) -> list[object]:
    value = mapping.get(name)
    if not isinstance(value, list):
        raise ValueError(f"plan {name} must be an array")
    return value


def _string(mapping: dict[str, object], name: str) -> str:
    value = mapping.get(name)
    if not isinstance(value, str):
        raise ValueError(f"plan {name} must be a string")
    return value


def _string_value(value: object, name: str) -> str:
    if not isinstance(value, str):
        raise ValueError(f"plan {name} must contain strings")
    return value


def _integer(mapping: dict[str, object], name: str) -> int:
    value = mapping.get(name)
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"plan {name} must be an integer")
    return value


def _bool(mapping: dict[str, object], name: str) -> bool:
    value = mapping.get(name)
    if not isinstance(value, bool):
        raise ValueError(f"plan {name} must be a boolean")
    return value
