from __future__ import annotations

import json
from pathlib import Path

from jsonschema import Draft202012Validator

from modelable.compiler.workspace import Workspace
from modelable.governance.por import build_por_reference
from modelable.emitters.diagnostics import type_loss
from modelable.parser.ir import (
    AnnClassification,
    AnnDeprecated,
    AnnKey,
    AnnOwner,
    AnnPii,
    AnnServer,
    ArrayType,
    ComputedMapping,
    DecimalType,
    DirectMapping,
    EnumType,
    FieldDef,
    MapType,
    ModelVersion,
    NamedType,
    ObjectType,
    PrimitiveType,
    ProjectionVersion,
    RefType,
)
from modelable.emitters.base import EmittedArtifact
from modelable.emitters.diagnostics import validation_failed


def emit_json_schema(workspace: Workspace, out_dir: Path) -> list[EmittedArtifact]:
    """Emit JSON Schema 2020-12 artifacts for every model and projection version."""
    # Build lookup for resolving projection field types from source models.
    model_lookup: dict[tuple[str, str, int], ModelVersion] = {}
    for domain in workspace.mdl.domains:
        for model_name, versions in domain.models.items():
            for version in versions:
                model_lookup[(domain.name, model_name, version.version)] = version

    artifacts: list[EmittedArtifact] = []
    for domain in workspace.mdl.domains:
        for model_name, versions in domain.models.items():
            for version in versions:
                artifact = _emit_model_version(domain.name, model_name, version, out_dir)
                artifacts.append(artifact)

        for projection_name, versions in domain.projections.items():
            for version in versions:
                artifact = _emit_projection_version(
                    domain.name, projection_name, version, out_dir, model_lookup
                )
                artifacts.append(artifact)
    return artifacts


def _artifact_id(domain: str, name: str, version: int) -> str:
    return f"{domain}.{name}.v{version}"


def _emit_model_version(
    domain: str, model_name: str, version: ModelVersion, out_dir: Path
) -> EmittedArtifact:
    artifact_id = _artifact_id(domain, model_name, version.version)
    schema: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": artifact_id,
        "type": "object",
        "title": model_name,
        "x-modelable": {
            "domain": domain,
            "name": model_name,
            "kind": version.model_kind.value,
            "version": version.version,
            "changeKind": version.change_kind.value,
        },
        "x-modelable-por": build_por_reference(f"{domain}.{model_name}.v{version.version}"),
    }

    properties: dict[str, dict] = {}
    required: list[str] = []
    warnings: list[str] = []

    for field in version.fields:
        prop = _field_to_json_schema(field, field.type)
        if isinstance(field.type, NamedType):
            warnings.append(type_loss(field.type.name))
        properties[field.name] = prop
        if not field.optional:
            required.append(field.name)

    schema["properties"] = properties
    if required:
        schema["required"] = required

    path = out_dir / f"{artifact_id}.json"
    artifact = EmittedArtifact(
        target="json-schema",
        ref=f"{domain}.{model_name}@{version.version}",
        artifact_id=artifact_id,
        path=path,
        content=schema,
        warnings=warnings,
    )

    _validate_schema(artifact)
    return artifact


def _emit_projection_version(
    domain: str,
    projection_name: str,
    version: ProjectionVersion,
    out_dir: Path,
    model_lookup: dict[tuple[str, str, int], ModelVersion],
) -> EmittedArtifact:
    artifact_id = _artifact_id(domain, projection_name, version.version)
    schema: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": artifact_id,
        "type": "object",
        "title": projection_name,
        "x-modelable": {
            "domain": domain,
            "name": projection_name,
            "kind": "projection",
            "version": version.version,
            "source": {
                "model": version.source.model,
                "version": _version_spec_to_json(version.source.version),
                "alias": version.source.alias,
            },
            "autoGenerated": version.auto_generated,
        },
        "x-modelable-por": build_por_reference(
            f"{domain}.{projection_name}.v{version.version}"
        ),
    }

    if version.joins:
        schema["x-modelable"]["joins"] = [
            {
                "model": join.model,
                "version": _version_spec_to_json(join.version),
                "alias": join.alias,
                "on": join.on,
            }
            for join in version.joins
        ]

    if version.group_by:
        schema["x-modelable"]["groupBy"] = version.group_by

    properties: dict[str, dict] = {}
    required: list[str] = []
    warnings: list[str] = []

    for field in version.fields:
        field_type = _resolve_projection_field_type(field, version, model_lookup)
        prop = _field_to_json_schema(field, field_type)
        if isinstance(field_type, NamedType):
            warnings.append(type_loss(field_type.name))
        _add_lineage(prop, field, version)
        properties[field.name] = prop
        # Projection fields are always required in the current IR (no ? syntax).
        required.append(field.name)

    schema["properties"] = properties
    if required:
        schema["required"] = required

    path = out_dir / f"{artifact_id}.json"
    artifact = EmittedArtifact(
        target="json-schema",
        ref=f"{domain}.{projection_name}@{version.version}",
        artifact_id=artifact_id,
        path=path,
        content=schema,
        warnings=warnings,
    )

    _validate_schema(artifact)
    return artifact


def _version_spec_to_json(version_spec) -> dict:
    from modelable.parser.ir import VersionExact, VersionRange, VersionMin

    if isinstance(version_spec, VersionExact):
        return {"kind": "exact", "version": version_spec.version}
    if isinstance(version_spec, VersionRange):
        return {
            "kind": "range",
            "minInclusive": version_spec.min_inclusive,
            "maxExclusive": version_spec.max_exclusive,
        }
    if isinstance(version_spec, VersionMin):
        return {"kind": "min", "minInclusive": version_spec.min_inclusive}
    return {}


def _resolve_projection_field_type(
    field: FieldDef,
    projection: ProjectionVersion,
    model_lookup: dict[tuple[str, str, int], ModelVersion],
):
    """Resolve the JSON Schema type for a projection field from its source model."""
    if not isinstance(field.mapping, DirectMapping):
        return None

    # Find the source model version that matches the projection source.
    source_fqn = projection.source.model
    try:
        source_domain, source_model = source_fqn.rsplit(".", 1)
    except ValueError:
        return None

    # For auto-generated projections the version is exact; for explicit
    # projections we use the version declared in the source clause.
    from modelable.parser.ir import VersionExact

    if isinstance(projection.source.version, VersionExact):
        source_version = projection.source.version.version
    else:
        # Fall back to the projection's own version for ranges/min specs.
        source_version = projection.version

    source_mv = model_lookup.get((source_domain, source_model, source_version))
    if source_mv is None:
        return None

    for src_field in source_mv.fields:
        if src_field.name == field.mapping.source_field:
            return src_field.type

    return None


def _field_to_json_schema(field: FieldDef, field_type=None) -> dict:
    prop = _type_to_json_schema(field_type) if field_type is not None else {}

    for ann in field.annotations:
        if isinstance(ann, AnnKey):
            prop["x-modelable-field"] = {**(prop.get("x-modelable-field") or {}), "key": True}
        elif isinstance(ann, AnnPii):
            prop["x-modelable-field"] = {**(prop.get("x-modelable-field") or {}), "pii": True}
        elif isinstance(ann, AnnClassification):
            prop["x-modelable-classification"] = ann.level
        elif isinstance(ann, AnnDeprecated):
            prop["deprecated"] = True
            prop["x-modelable-field"] = {
                **(prop.get("x-modelable-field") or {}),
                "replacedBy": ann.replaced_by,
            }
        elif isinstance(ann, AnnOwner):
            prop["x-modelable-field"] = {
                **(prop.get("x-modelable-field") or {}),
                "owner": ann.team,
            }
        elif isinstance(ann, AnnServer):
            prop["x-modelable-field"] = {
                **(prop.get("x-modelable-field") or {}),
                "server": True,
            }

    return prop


def _type_to_json_schema(field_type) -> dict:
    if isinstance(field_type, PrimitiveType):
        return _primitive_to_json_schema(field_type.kind)
    if isinstance(field_type, DecimalType):
        return {
            "type": "string",
            "pattern": r"^-?\d+(\.\d+)?$",
            "x-modelable-field": {"decimalPrecision": field_type.precision, "decimalScale": field_type.scale},
        }
    if isinstance(field_type, ArrayType):
        return {
            "type": "array",
            "items": _type_to_json_schema(field_type.item),
        }
    if isinstance(field_type, MapType):
        return {
            "type": "object",
            "additionalProperties": _type_to_json_schema(field_type.value),
        }
    if isinstance(field_type, RefType):
        return {
            "type": "string",
            "x-modelable-ref": field_type.target,
        }
    if isinstance(field_type, EnumType):
        return {
            "type": "string",
            "enum": field_type.values,
        }
    if isinstance(field_type, NamedType):
        # MVP: named value objects without a registry lookup are emitted as
        # object placeholders with the type name preserved.
        return {
            "type": "object",
            "x-modelable-field": {"namedType": field_type.name},
        }
    if isinstance(field_type, ObjectType):
        prop: dict = {"type": "object"}
        props: dict[str, dict] = {}
        req: list[str] = []
        for f in field_type.fields:
            props[f.name] = _field_to_json_schema(f)
            if not f.optional:
                req.append(f.name)
        prop["properties"] = props
        if req:
            prop["required"] = req
        return prop

    return {"type": "object"}


def _primitive_to_json_schema(kind: str) -> dict:
    mapping: dict[str, dict] = {
        "string": {"type": "string"},
        "bool": {"type": "boolean"},
        "int": {"type": "integer", "format": "int64"},
        "float": {"type": "number"},
        "uuid": {"type": "string", "format": "uuid"},
        "timestamp": {"type": "string", "format": "date-time"},
        "date": {"type": "string", "format": "date"},
        "time": {"type": "string", "format": "time"},
        "duration": {"type": "string", "format": "duration"},
        "binary": {"type": "string", "contentEncoding": "base64"},
    }
    return mapping.get(kind, {"type": "string"})


def _add_lineage(prop: dict, field: FieldDef, projection: ProjectionVersion) -> None:
    mapping = field.mapping
    if isinstance(mapping, DirectMapping):
        prop["x-modelable-lineage"] = {
            "kind": "direct",
            "source": f"{mapping.source_alias}.{mapping.source_field}",
            "sourceModel": projection.source.model,
        }
    elif isinstance(mapping, ComputedMapping):
        prop["x-modelable-lineage"] = {
            "kind": "computed",
            "expression": mapping.expression,
        }


def _validate_schema(artifact: EmittedArtifact) -> None:
    try:
        Draft202012Validator.check_schema(artifact.content)
    except Exception as exc:
        artifact.warnings.append(
            validation_failed(str(artifact.path), str(exc))
        )
