from __future__ import annotations

from pathlib import PurePath, PurePosixPath

from jsonschema import Draft202012Validator

from modelable.compiler.workspace import Workspace
from modelable.emitters._schema_mapping import (
    _field_to_json_schema,
    _resolve_projection_field_type,
    _resolve_projection_source_field,
)
from modelable.emitters.base import EmittedArtifact, compute_content_hash
from modelable.emitters.diagnostics import type_loss, validation_failed
from modelable.governance.por import build_por_reference
from modelable.parser.ir import (
    ComputedMapping,
    DirectMapping,
    DomainDef,
    FieldDef,
    ModelVersion,
    NamedType,
    PrimitiveType,
    ProjectionField,
    ProjectionVersion,
    VersionExact,
    VersionMin,
    VersionPinned,
    VersionRange,
)


def emit_json_schema(workspace: Workspace, out_dir: PurePath) -> list[EmittedArtifact]:
    """Emit JSON Schema 2020-12 artifacts for every model and projection version."""
    artifacts: list[EmittedArtifact] = []
    for domain in workspace.mdl.domains:
        for model_name, versions in domain.models.items():
            for version in versions:
                artifact = _emit_model_version(domain, model_name, version, out_dir)
                artifacts.append(artifact)

        for projection_name, versions in domain.projections.items():
            for version in versions:
                artifact = _emit_projection_version(domain, projection_name, version, out_dir, workspace.mdl)
                artifacts.append(artifact)
    return artifacts


def emit_json_schema_artifacts(workspace: Workspace) -> list[EmittedArtifact]:
    """Return deterministic JSON Schema artifacts without writing files."""
    return emit_json_schema(workspace, PurePosixPath())


def _artifact_id(domain: str, name: str, version: int) -> str:
    return f"{domain}.{name}.v{version}"


def _emit_model_version(
    domain: DomainDef, model_name: str, version: ModelVersion, out_dir: PurePath
) -> EmittedArtifact:
    artifact_id = _artifact_id(domain.name, model_name, version.version)
    schema: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": artifact_id,
        "type": "object",
        "title": model_name,
        "x-modelable": {
            "domain": domain.name,
            "name": model_name,
            "kind": version.model_kind.value,
            "version": version.version,
            "changeKind": version.change_kind.value,
        },
        "x-modelable-por": build_por_reference(f"{domain.name}.{model_name}.v{version.version}"),
    }
    _add_domain_metadata(schema["x-modelable"], domain)

    properties: dict[str, dict] = {}
    required: list[str] = []
    warnings: list[str] = []
    defs: dict[str, dict] = {}

    for field in version.fields:
        prop = _field_to_json_schema(field, field.type, defs=defs, path=[field.name])
        default_value = _field_default(field)
        if default_value is not None:
            prop["default"] = default_value
        if isinstance(field.type, NamedType):
            warnings.append(type_loss(field.type.name))
        properties[field.name] = prop
        if not field.optional:
            required.append(field.name)

    schema["properties"] = properties
    if required:
        schema["required"] = required
    if defs:
        schema["$defs"] = defs

    path = out_dir / f"{artifact_id}.json"
    artifact = EmittedArtifact(
        target="json-schema",
        ref=f"{domain.name}.{model_name}@{version.version}",
        artifact_id=artifact_id,
        path=path,
        content=schema,
        content_hash=compute_content_hash(schema),
        warnings=warnings,
    )

    _validate_schema(artifact)
    return artifact


def _emit_projection_version(
    domain: DomainDef,
    projection_name: str,
    version: ProjectionVersion,
    out_dir: PurePath,
    mdl,
) -> EmittedArtifact:
    artifact_id = _artifact_id(domain.name, projection_name, version.version)
    schema: dict = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": artifact_id,
        "type": "object",
        "title": projection_name,
        "x-modelable": {
            "domain": domain.name,
            "name": projection_name,
            "kind": "projection",
            "version": version.version,
            "source": {
                "model": version.source.model,
                "version": _version_spec_to_json(version.source.version),
                "alias": version.source.alias,
            },
            "autoGenerated": version.auto_generated,
        },
        "x-modelable-por": build_por_reference(f"{domain.name}.{projection_name}.v{version.version}"),
    }
    _add_domain_metadata(schema["x-modelable"], domain)

    if version.joins:
        schema["x-modelable"]["joins"] = [
            {
                "model": join.model,
                "version": _version_spec_to_json(join.version),
                "alias": join.alias,
                "on": join.on,
            }
            for join in version.joins
        ]

    if version.where:
        schema["x-modelable"]["where"] = version.where

    if version.group_by:
        schema["x-modelable"]["groupBy"] = version.group_by

    properties: dict[str, dict] = {}
    required: list[str] = []
    warnings: list[str] = []
    defs: dict[str, dict] = {}

    for field in version.fields:
        field_type = _resolve_projection_field_type(field, version, mdl)
        source_field = _resolve_projection_source_field(field, version, mdl)
        prop = _field_to_json_schema(
            field,
            field_type,
            defs=defs,
            path=[field.name],
            inherited_constraints=source_field.constraints if source_field is not None else (),
        )
        if isinstance(field_type, NamedType):
            warnings.append(type_loss(field_type.name))
        _add_lineage(prop, field, version)
        properties[field.name] = prop
        # Projection fields are always required in the current IR (no ? syntax).
        required.append(field.name)

    schema["properties"] = properties
    if required:
        schema["required"] = required
    if defs:
        schema["$defs"] = defs

    path = out_dir / f"{artifact_id}.json"
    artifact = EmittedArtifact(
        target="json-schema",
        ref=f"{domain.name}.{projection_name}@{version.version}",
        artifact_id=artifact_id,
        path=path,
        content=schema,
        content_hash=compute_content_hash(schema),
        warnings=warnings,
    )

    _validate_schema(artifact)
    return artifact


def _version_spec_to_json(version_spec) -> dict:
    if isinstance(version_spec, VersionExact):
        return {"kind": "exact", "version": version_spec.version}
    if isinstance(version_spec, VersionRange):
        return {
            "kind": "range",
            "minInclusive": version_spec.min_inclusive,
            "maxExclusive": version_spec.max_exclusive,
        }
    if isinstance(version_spec, VersionMin):
        return {"kind": "min", "minInclusive": version_spec.min_inclusive}
    if isinstance(version_spec, VersionPinned):
        return {
            "kind": "pinned",
            "version": version_spec.version,
            "contentHash": version_spec.content_hash,
        }
    return {}


def _field_default(field: FieldDef):
    if field.default is None:
        return None
    raw = field.default.strip()
    if isinstance(field.type, PrimitiveType):
        if field.type.kind == "bool":
            if raw == "true":
                return True
            if raw == "false":
                return False
        if field.type.kind in {"int"}:
            try:
                return int(raw)
            except ValueError:
                return raw
        if field.type.kind in {"float"}:
            try:
                return float(raw)
            except ValueError:
                return raw
    if len(raw) >= 2 and raw[0] == '"' and raw[-1] == '"':
        return raw[1:-1]
    return raw


def _add_domain_metadata(container: dict, domain: DomainDef) -> None:
    if domain.owner is not None:
        container["owner"] = domain.owner
    if domain.contact is not None:
        container["contact"] = domain.contact
    if domain.description is not None:
        container["description"] = domain.description


def _add_lineage(prop: dict, field: ProjectionField, projection: ProjectionVersion) -> None:
    mapping = field.mapping
    if isinstance(mapping, DirectMapping):
        prop["x-modelable-lineage"] = {
            "kind": "direct",
            "source": f"{mapping.source_alias}.{mapping.source_field}",
            "sourceModel": projection.source.model,
        }
    elif isinstance(mapping, ComputedMapping):
        prop["x-modelable-lineage"] = {
            "kind": "computed",
            "expression": mapping.expression,
        }


def _validate_schema(artifact: EmittedArtifact) -> None:
    try:
        Draft202012Validator.check_schema(artifact.content)
    except Exception as exc:
        artifact.warnings.append(validation_failed(str(artifact.path), str(exc)))
