"""JSON Schema projection emission from validated ``modelable.plan/v0`` documents."""

from __future__ import annotations

from pathlib import PurePath
from typing import cast

from jsonschema import Draft202012Validator

from modelable.emitters.base import EmittedArtifact, compute_content_hash
from modelable.emitters.diagnostics import validation_failed
from modelable.governance.por import build_por_reference
from modelable.planner.protocol import PlanDocument, validate_plan

_INTEGER_BOUNDS = {
    "u8": (0, 2**8 - 1),
    "u16": (0, 2**16 - 1),
    "u32": (0, 2**32 - 1),
    "u64": (0, 2**64 - 1),
    "u128": (0, 2**128 - 1),
    "i8": (-(2**7), 2**7 - 1),
    "i16": (-(2**15), 2**15 - 1),
    "i32": (-(2**31), 2**31 - 1),
    "i64": (-(2**63), 2**63 - 1),
    "i128": (-(2**127), 2**127 - 1),
}


def emit_json_schema_plan(
    plan: PlanDocument,
    out_dir: PurePath,
    *,
    domain_owner: str | None = None,
    domain_contact: str | None = None,
    domain_description: str | None = None,
) -> EmittedArtifact:
    """Build one JSON Schema projection from a validated plan document."""
    document = validate_plan(plan)
    domain = _string(document, "domain")
    projection = _string(document, "projection")
    version = _integer(document, "version")
    artifact_id = f"{domain}.{projection}.v{version}"
    source = _mapping(document, "source")

    modelable: dict[str, object] = {
        "domain": domain,
        "name": projection,
        "kind": "projection",
        "version": version,
        "source": {
            "model": _string(source, "model"),
            "version": _version_spec(_mapping(source, "version")),
            "alias": _string(source, "alias"),
        },
        "autoGenerated": _bool(document, "auto_generated"),
    }
    _add_domain_metadata(modelable, domain_owner, domain_contact, domain_description)
    joins = _list(document, "joins")
    if joins:
        modelable["joins"] = [
            {
                "model": _string(_mapping_value(join, "join"), "model"),
                "version": _version_spec(_mapping(_mapping_value(join, "join"), "version")),
                "alias": _string(_mapping_value(join, "join"), "alias"),
                "on": _string(_mapping_value(join, "join"), "on"),
            }
            for join in joins
        ]
    where = document.get("where")
    if where:
        modelable["where"] = where
    group_by = _list(document, "group_by")
    if group_by:
        modelable["groupBy"] = group_by

    schema: dict[str, object] = {
        "$schema": "https://json-schema.org/draft/2020-12/schema",
        "$id": artifact_id,
        "type": "object",
        "title": projection,
        "x-modelable": modelable,
        "x-modelable-por": build_por_reference(f"{domain}.{projection}.v{version}"),
    }
    properties: dict[str, dict[str, object]] = {}
    definitions: dict[str, dict[str, object]] = {}
    fields = _list(document, "fields")
    source_fields = _source_fields(source)
    required: list[str] = []
    for value in fields:
        field = _mapping_value(value, "field")
        source_field = _source_field(field, source_fields)
        prop = _field_schema(
            field,
            _mapping_or_none(field.get("type")),
            definitions,
            [_string(field, "name")],
            inherited_constraints=_constraints(source_field),
        )
        _add_lineage(prop, field, source)
        properties[_string(field, "name")] = prop
        required.append(_string(field, "name"))
    schema["properties"] = properties
    if required:
        schema["required"] = required
    if definitions:
        schema["$defs"] = definitions

    artifact = EmittedArtifact(
        target="json-schema",
        ref=f"{domain}.{projection}@{version}",
        artifact_id=artifact_id,
        path=out_dir / f"{artifact_id}.json",
        content=schema,
        content_hash=compute_content_hash(schema),
    )
    try:
        Draft202012Validator.check_schema(schema)
    except Exception as exc:
        artifact.warnings.append(validation_failed(str(artifact.path), str(exc)))
    return artifact


def _field_schema(
    field: dict[str, object],
    field_type: dict[str, object] | None,
    definitions: dict[str, dict[str, object]],
    path: list[str],
    *,
    inherited_constraints: list[dict[str, object]],
) -> dict[str, object]:
    prop = _type_schema(field_type, definitions, path)
    if field.get("nullable"):
        if isinstance(prop.get("type"), str):
            prop["type"] = [prop["type"], "null"]
        else:
            prop = {"anyOf": [prop, {"type": "null"}]}

    annotations = _list_if_present(field.get("annotations"))
    wire_targets: dict[str, object] = {}
    for annotation in annotations:
        ann = _mapping_value(annotation, "annotation")
        kind = _string(ann, "kind")
        if kind == "key":
            prop["x-modelable-field"] = {**_mapping_or_empty(prop.get("x-modelable-field")), "key": True}
        elif kind == "pii":
            prop["x-modelable-field"] = {**_mapping_or_empty(prop.get("x-modelable-field")), "pii": True}
        elif kind == "classification":
            prop["x-modelable-classification"] = _string(ann, "level")
        elif kind == "deprecated":
            prop["deprecated"] = True
            prop["x-modelable-field"] = {
                **_mapping_or_empty(prop.get("x-modelable-field")),
                "replacedBy": _string(ann, "replaced_by"),
            }
        elif kind == "owner":
            prop["x-modelable-field"] = {
                **_mapping_or_empty(prop.get("x-modelable-field")),
                "owner": _string(ann, "team"),
            }
        elif kind == "server":
            prop["x-modelable-field"] = {**_mapping_or_empty(prop.get("x-modelable-field")), "server": True}
        elif kind == "wire":
            wire_targets = _mapping(ann, "targets")
    if wire_targets:
        prop["x-modelable-wire"] = {
            target: _wire_hint(_mapping_value(hint, "wire hint")) for target, hint in sorted(wire_targets.items())
        }

    for constraint in [*inherited_constraints, *_constraints(field)]:
        kind = _string(constraint, "kind")
        value = constraint.get("value")
        if kind == "min" and isinstance(value, (int, float)):
            prop["minimum"] = value
        elif kind == "max" and isinstance(value, (int, float)):
            prop["maximum"] = value
        else:
            key = {
                "min_length": "minLength",
                "max_length": "maxLength",
                "min_items": "minItems",
                "max_items": "maxItems",
                "unique_items": "uniqueItems",
                "pattern": "pattern",
                "format": "format",
            }.get(kind)
            if key is not None:
                prop[key] = value
    json_hint = wire_targets.get("json")
    if (
        isinstance(json_hint, dict)
        and json_hint.get("encoding") == "string"
        and field_type is not None
        and (field_type.get("kind") == "decimal" or field_type.get("kind") == "int")
    ):
        prop["type"] = "string"
        prop.pop("format", None)
    return prop


def _type_schema(
    field_type: dict[str, object] | None,
    definitions: dict[str, dict[str, object]],
    path: list[str],
) -> dict[str, object]:
    if field_type is None:
        return {}
    kind = field_type.get("kind")
    if kind in _INTEGER_BOUNDS:
        low, high = _INTEGER_BOUNDS[kind]
        return {"type": "integer", "minimum": low, "maximum": high}
    primitives: dict[str, dict[str, object]] = {
        "string": {"type": "string"},
        "bool": {"type": "boolean"},
        "int": {"type": "integer", "format": "int64"},
        "float": {"type": "number"},
        "uuid": {"type": "string", "format": "uuid"},
        "timestamp": {"type": "string", "format": "date-time"},
        "date": {"type": "string", "format": "date"},
        "time": {"type": "string", "format": "time"},
        "duration": {"type": "string", "format": "duration"},
        "binary": {"type": "string", "contentEncoding": "base64"},
        "json": {},
    }
    if kind in primitives:
        schema = dict(primitives[kind])
        if kind == "uuid" and field_type.get("version") == 7:
            schema["x-modelable-uuid-version"] = 7
        return schema
    if kind == "decimal":
        return {
            "type": "string",
            "pattern": r"^-?\d+(\.\d+)?$",
            "x-modelable-field": {
                "decimalPrecision": field_type.get("precision"),
                "decimalScale": field_type.get("scale"),
            },
        }
    if kind == "fixed_binary":
        return {"type": "string", "contentEncoding": "base64", "x-modelable-fixed-length": field_type.get("length")}
    if kind == "array":
        return {"type": "array", "items": _type_schema(_mapping_or_none(field_type.get("item")), definitions, path)}
    if kind == "map":
        return {
            "type": "object",
            "additionalProperties": _type_schema(_mapping_or_none(field_type.get("value")), definitions, path),
        }
    if kind == "ref":
        target = field_type.get("target")
        version = field_type.get("version")
        if isinstance(target, str) and isinstance(version, dict) and version.get("kind") in {"exact", "pinned"}:
            return {"$ref": f"#/$defs/{target}.v{version.get('version')}"}
        return {"type": "string", "x-modelable-ref": target}
    if kind == "enum":
        return {"type": "string", "enum": field_type.get("values", [])}
    if kind == "enum_ref":
        values = field_type.get("values")
        if isinstance(values, list):
            name = _string(field_type, "name")
            domain = field_type.get("declaring_domain")
            definition = _definition_name([domain, name] if isinstance(domain, str) else [name])
            definitions.setdefault(definition, {"title": name, "type": "string", "enum": values})
            return {"$ref": f"#/$defs/{definition}"}
        return {"type": "string"}
    if kind == "named":
        name = _string(field_type, "name")
        definition = _definition_name([name])
        definitions.setdefault(definition, {"title": name, "type": "object", "x-modelable-field": {"namedType": name}})
        return {"$ref": f"#/$defs/{definition}"}
    if kind == "object":
        definition = _definition_name(path or ["InlineObject"])
        fields = _list(field_type, "fields")
        props: dict[str, dict[str, object]] = {}
        required: list[str] = []
        for value in fields:
            child = _mapping_value(value, "object field")
            props[_string(child, "name")] = _field_schema(
                child,
                _mapping_or_none(child.get("type")),
                definitions,
                [*path, _string(child, "name")],
                inherited_constraints=[],
            )
            if child.get("optional") is not True:
                required.append(_string(child, "name"))
        object_schema: dict[str, object] = {"title": definition, "type": "object", "properties": props}
        if required:
            object_schema["required"] = required
        definitions.setdefault(definition, object_schema)
        return {"$ref": f"#/$defs/{definition}"}
    if kind == "union":
        variants: list[dict[str, object]] = []
        mapping: dict[str, object] = {}
        discriminator = _string(field_type, "discriminator")
        for value in _list(field_type, "variants"):
            variant = _mapping_value(value, "union variant")
            tag = _string(variant, "tag")
            variant_schema = _type_schema(_mapping_or_none(variant.get("type")), definitions, [*path, tag])
            variants.append(
                {
                    "allOf": [
                        variant_schema,
                        {"type": "object", "properties": {discriminator: {"const": tag}}, "required": [discriminator]},
                    ]
                }
            )
            mapping[tag] = variant_schema.get("$ref", "#")
        return {"oneOf": variants, "discriminator": {"propertyName": discriminator, "mapping": mapping}}
    return {"type": "object"}


def _add_lineage(prop: dict[str, object], field: dict[str, object], source: dict[str, object]) -> None:
    kind = _string(field, "kind")
    if kind == "direct":
        prop["x-modelable-lineage"] = {
            "kind": "direct",
            "source": f"{_string(field, 'source_alias')}.{_string(field, 'source_field')}",
            "sourceModel": _string(source, "model"),
        }
    elif kind == "computed":
        prop["x-modelable-lineage"] = {"kind": "computed", "expression": _string(field, "expression")}


def _source_fields(source: dict[str, object]) -> list[dict[str, object]]:
    resolved = source.get("resolved")
    if not isinstance(resolved, dict):
        return []
    return [
        cast(dict[str, object], value)
        for value in _list(cast(dict[str, object], resolved), "fields")
        if isinstance(value, dict)
    ]


def _source_field(field: dict[str, object], source_fields: list[dict[str, object]]) -> dict[str, object] | None:
    if field.get("kind") != "direct":
        return None
    name = field.get("source_field")
    return next((candidate for candidate in source_fields if candidate.get("name") == name), None)


def _constraints(field: dict[str, object] | None) -> list[dict[str, object]]:
    if field is None:
        return []
    constraints = field.get("constraints")
    if not isinstance(constraints, list):
        return []
    return [cast(dict[str, object], value) for value in constraints if isinstance(value, dict)]


def _wire_hint(value: dict[str, object]) -> dict[str, object]:
    return {
        key: value[key]
        for key in ("encoding", "type", "case", "overrides")
        if value.get(key) is not None and value.get(key) not in ({}, [])
    }


def _version_spec(value: dict[str, object]) -> dict[str, object]:
    return dict(value)


def _definition_name(path: list[str]) -> str:
    return "".join(part[:1].upper() + part[1:] for part in path if part)


def _add_domain_metadata(
    container: dict[str, object], owner: str | None, contact: str | None, description: str | None
) -> None:
    if owner is not None:
        container["owner"] = owner
    if contact is not None:
        container["contact"] = contact
    if description is not None:
        container["description"] = description


def _mapping(mapping: dict[str, object], name: str) -> dict[str, object]:
    return _mapping_value(mapping.get(name), name)


def _mapping_value(value: object, name: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"plan {name} must be an object")
    return cast(dict[str, object], value)


def _mapping_or_none(value: object) -> dict[str, object] | None:
    return cast(dict[str, object], value) if isinstance(value, dict) else None


def _mapping_or_empty(value: object) -> dict[str, object]:
    return cast(dict[str, object], value) if isinstance(value, dict) else {}


def _list(mapping: dict[str, object], name: str) -> list[object]:
    value = mapping.get(name)
    if not isinstance(value, list):
        raise ValueError(f"plan {name} must be an array")
    return value


def _list_if_present(value: object) -> list[object]:
    return value if isinstance(value, list) else []


def _string(mapping: dict[str, object], name: str) -> str:
    value = mapping.get(name)
    if not isinstance(value, str):
        raise ValueError(f"plan {name} must be a string")
    return value


def _integer(mapping: dict[str, object], name: str) -> int:
    value = mapping.get(name)
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"plan {name} must be an integer")
    return value


def _bool(mapping: dict[str, object], name: str) -> bool:
    value = mapping.get(name)
    if not isinstance(value, bool):
        raise ValueError(f"plan {name} must be a boolean")
    return value
