"""ODCS projection emission from validated ``modelable.plan/v1`` documents."""

from __future__ import annotations

from pathlib import Path
from typing import cast

import yaml

from modelable.emitters.base import EmittedArtifact, compute_content_hash
from modelable.planner.protocol import PlanDocument, validate_plan

ODCS_VERSION = "v3.1.0"


def emit_odcs_projection_plan(
    plan: PlanDocument,
    out_dir: Path,
    *,
    domain_description: str | None = None,
    domain_owner: str | None = None,
    domain_contact: str | None = None,
) -> EmittedArtifact:
    """Build one ODCS projection contract from a validated plan document."""
    document = validate_plan(plan)
    domain = _string(document, "domain")
    projection = _string(document, "projection")
    version = _integer(document, "version")
    ref = f"{domain}.{projection}@{version}"
    source = _mapping(document, "source")
    source_ref = f"{_string(source, 'model')}@{_version_label(_mapping(source, 'version'))}"

    schema_custom_properties: dict[str, object] = {
        "modelableKind": "projection",
        "modelableSource": source_ref,
    }
    if document.get("where"):
        schema_custom_properties["modelableWhere"] = document["where"]
    group_by = _list(document, "group_by")
    if group_by:
        schema_custom_properties["modelableGroupBy"] = group_by

    custom_properties: dict[str, object] = {
        "modelableRef": ref,
        "modelableKind": "projection",
    }
    if domain_owner:
        custom_properties["modelableOwner"] = domain_owner
    if domain_contact:
        custom_properties["modelableContact"] = domain_contact
    custom_properties["modelableSource"] = source_ref

    doc: dict[str, object] = {
        "apiVersion": ODCS_VERSION,
        "kind": "DataContract",
        "id": f"modelable://{domain}/{projection}/v{version}",
        "name": f"{domain}.{projection}.v{version}",
        "version": str(version),
        "domain": domain,
        "status": "active",
        "description": {"purpose": domain_description or f"Modelable projection contract for {ref}"},
        "schema": [
            {
                "name": projection,
                "logicalType": "object",
                "physicalName": projection,
                "properties": [_field_property(field) for field in _list(document, "fields")],
                "customProperties": _custom_properties(schema_custom_properties),
            }
        ],
        "authoritativeDefinitions": [{"url": f"modelable:{ref}", "type": "modelable"}],
        "customProperties": _custom_properties(custom_properties),
    }
    content = f"# @generated by Modelable\n{yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)}"
    artifact_id = f"{domain}.{projection}.v{version}"
    return EmittedArtifact(
        target="odcs",
        ref=ref,
        artifact_id=artifact_id,
        path=out_dir / f"{artifact_id}.odcs.yaml",
        content=content,
        content_hash=compute_content_hash(content),
    )


def _field_property(value: object) -> dict[str, object]:
    field = _mapping_value(value, "field")
    field_type = field.get("type")
    type_info = _type_info(field_type if isinstance(field_type, dict) else None)
    prop: dict[str, object] = {
        "name": _string(field, "name"),
        "logicalType": type_info["logicalType"],
        "required": field.get("optional") is not True,
        "customProperties": _custom_properties({"modelableType": type_info["modelable_type"]}),
    }
    if "logicalTypeOptions" in type_info:
        prop["logicalTypeOptions"] = type_info["logicalTypeOptions"]
    if "enum" in type_info:
        cast(list[dict[str, object]], prop["customProperties"]).append(
            {"property": "modelableEnum", "value": type_info["enum"]}
        )
    if type_info.get("extra"):
        cast(list[dict[str, object]], prop["customProperties"]).extend(
            _custom_properties(cast(dict[str, object], type_info["extra"]))
        )

    classification = field.get("classification")
    if isinstance(classification, str) and classification:
        prop["classification"] = classification
    governance: dict[str, object] = {}
    if _bool(field, "pii"):
        governance["modelablePii"] = True
    owner = field.get("owner")
    if isinstance(owner, str) and owner:
        governance["modelableOwner"] = owner
    cast(list[dict[str, object]], prop["customProperties"]).extend(_custom_properties(governance))

    kind = _string(field, "kind")
    mapping: dict[str, object] = {"modelableMapping": kind}
    if kind == "direct":
        lineage = _list(field, "lineage")
        mapping["modelableLineage"] = lineage
    elif kind == "computed":
        mapping["modelableExpression"] = _string(field, "expression")
    cast(list[dict[str, object]], prop["customProperties"]).extend(_custom_properties(mapping))
    return prop


def _type_info(field_type: dict[str, object] | None) -> dict[str, object]:
    if field_type is None:
        return {"logicalType": "string", "modelable_type": "unknown"}
    kind = field_type.get("kind")
    if kind == "uuid":
        return {"logicalType": "string", "modelable_type": "uuid", "logicalTypeOptions": {"format": "uuid"}}
    if kind in {
        "string",
        "int",
        "float",
        "bool",
        "date",
        "time",
        "timestamp",
        "uuid",
        "duration",
        "binary",
        "json",
        "u8",
        "u16",
        "u32",
        "u64",
        "u128",
        "i8",
        "i16",
        "i32",
        "i64",
        "i128",
    }:
        return {"logicalType": kind, "modelable_type": kind}
    if kind == "decimal":
        precision = field_type.get("precision")
        scale = field_type.get("scale")
        return {
            "logicalType": "number",
            "modelable_type": f"decimal({precision},{scale})",
            "extra": {"modelablePrecision": precision, "modelableScale": scale},
        }
    if kind == "array":
        item = field_type.get("item")
        return {
            "logicalType": "array",
            "modelable_type": f"array<{_type_name(item)}>",
            "extra": {"modelableItemType": _type_name(item)},
        }
    if kind == "map":
        key = field_type.get("key")
        value = field_type.get("value")
        return {
            "logicalType": "object",
            "modelable_type": f"map<{_type_name(key)},{_type_name(value)}>",
            "extra": {"modelableKeyType": _type_name(key), "modelableValueType": _type_name(value)},
        }
    if kind == "ref":
        target = _string(field_type, "target")
        return {"logicalType": "string", "modelable_type": f"ref<{target}>", "extra": {"modelableRef": target}}
    if kind == "enum":
        values = cast(list[object], field_type.get("values", []))
        return {"logicalType": "string", "modelable_type": "enum(" + ",".join(map(str, values)) + ")", "enum": values}
    if kind == "enum_ref":
        name = _string(field_type, "name")
        declaring_domain = field_type.get("declaring_domain")
        qualified_name = f"{declaring_domain}.{name}" if isinstance(declaring_domain, str) else name
        result: dict[str, object] = {
            "logicalType": "string",
            "modelable_type": qualified_name,
            "extra": {"modelableEnumType": qualified_name},
        }
        enum_values = field_type.get("values")
        if isinstance(enum_values, list):
            result["enum"] = enum_values
        return result
    if kind == "named":
        name = _string(field_type, "name")
        return {"logicalType": "object", "modelable_type": name, "extra": {"modelableNamedType": name}}
    if kind == "object":
        return {"logicalType": "object", "modelable_type": "object"}
    return {"logicalType": "string", "modelable_type": "unknown"}


def _type_name(value: object) -> str:
    if not isinstance(value, dict):
        return "unknown"
    kind = value.get("kind")
    if kind in {
        "string",
        "int",
        "float",
        "bool",
        "date",
        "time",
        "timestamp",
        "uuid",
        "duration",
        "binary",
        "json",
        "u8",
        "u16",
        "u32",
        "u64",
        "u128",
        "i8",
        "i16",
        "i32",
        "i64",
        "i128",
    }:
        return cast(str, kind)
    if kind == "decimal":
        return f"decimal({value.get('precision')},{value.get('scale')})"
    if kind == "array":
        return f"array<{_type_name(value.get('item'))}>"
    if kind == "map":
        return f"map<{_type_name(value.get('key'))},{_type_name(value.get('value'))}>"
    if kind == "ref":
        return f"ref<{value.get('target')}>"
    if kind == "enum":
        return "enum(" + ",".join(map(str, cast(list[object], value.get("values", [])))) + ")"
    return cast(str, value.get("name", kind or "unknown"))


def _version_label(version: dict[str, object]) -> str:
    kind = _string(version, "kind")
    if kind in {"exact", "pinned"}:
        label = str(_integer(version, "version"))
        if kind == "pinned":
            label += f"#{_string(version, 'contentHash')}"
        return label
    if kind == "range":
        return f">={_integer(version, 'minInclusive')}<{_integer(version, 'maxExclusive')}"
    return f">={_integer(version, 'minInclusive')}"


def _custom_properties(properties: dict[str, object]) -> list[dict[str, object]]:
    return [{"property": key, "value": value} for key, value in properties.items()]


def _mapping(mapping: dict[str, object], name: str) -> dict[str, object]:
    return _mapping_value(mapping.get(name), name)


def _mapping_value(value: object, name: str) -> dict[str, object]:
    if not isinstance(value, dict):
        raise ValueError(f"plan {name} must be an object")
    return value


def _list(mapping: dict[str, object], name: str) -> list[object]:
    value = mapping.get(name)
    if not isinstance(value, list):
        raise ValueError(f"plan {name} must be an array")
    return value


def _string(mapping: dict[str, object], name: str) -> str:
    value = mapping.get(name)
    if not isinstance(value, str):
        raise ValueError(f"plan {name} must be a string")
    return value


def _integer(mapping: dict[str, object], name: str) -> int:
    value = mapping.get(name)
    if not isinstance(value, int) or isinstance(value, bool):
        raise ValueError(f"plan {name} must be an integer")
    return value


def _bool(mapping: dict[str, object], name: str) -> bool:
    value = mapping.get(name)
    if not isinstance(value, bool):
        raise ValueError(f"plan {name} must be a boolean")
    return value
