from __future__ import annotations

import re
from pathlib import Path

from modelable.compiler.workspace import Workspace
from modelable.emitters.base import EmittedArtifact, compute_content_hash
from modelable.emitters.diagnostics import type_loss
from modelable.parser.ir import (
    ArrayType,
    DecimalType,
    DirectMapping,
    DomainDef,
    EnumType,
    FixedBinaryType,
    MapType,
    MdlFile,
    NamedType,
    ObjectType,
    PrimitiveType,
    ProjectionVersion,
    RefType,
)
from modelable.registry.resolver import resolve_model_ref

_DIALECTS = {"postgres", "clickhouse"}


def emit_sql(workspace: Workspace, out_dir: Path, dialect: str) -> list[EmittedArtifact]:
    """Emit CREATE TABLE SQL for every projection in the workspace.

    dialect must be "postgres" or "clickhouse".
    """
    if dialect not in _DIALECTS:
        raise ValueError(f"unsupported SQL dialect: {dialect!r}")

    artifacts: list[EmittedArtifact] = []
    for domain in workspace.mdl.domains:
        for projection_name, versions in domain.projections.items():
            for version in versions:
                art = _emit_projection_ddl(domain, projection_name, version, out_dir, workspace.mdl, dialect)
                if art is not None:
                    artifacts.append(art)
    return artifacts


def _emit_projection_ddl(
    domain: DomainDef,
    projection_name: str,
    version: ProjectionVersion,
    out_dir: Path,
    mdl: MdlFile,
    dialect: str,
) -> EmittedArtifact | None:
    artifact_id = f"{domain.name}.{projection_name}.v{version.version}"
    table_name = _resolve_table_name(version, mdl, dialect) or _snake_case(projection_name)

    columns: list[str] = []
    checks: list[str] = []
    warnings: list[str] = []

    for field in version.fields:
        field_type = _resolve_field_type(field, version, mdl)
        col_name = _snake_case(field.name)
        if field_type is None:
            warnings.append(type_loss(f"{domain.name}.{projection_name}.{field.name}"))
            col_type = "TEXT" if dialect == "postgres" else "String"
        else:
            wire = _resolve_merged_wire(field, version, mdl)
            optional = _is_optional(field, version, mdl)
            if dialect == "postgres":
                col_type = _pg_col_type(field_type, wire, optional=optional)
                if _pg_needs_unsigned_check(field_type):
                    checks.append(f"    CHECK ({col_name} >= 0)")
                if isinstance(field_type, FixedBinaryType):
                    checks.append(f"    CHECK (octet_length({col_name}) = {field_type.length})")
            else:
                col_type = _ch_col_type(field_type, wire, optional=optional)
        columns.append(f"    {col_name} {col_type}")

    if not columns:
        return None

    lines = ["-- @generated by Modelable"]
    lines.append(f"-- {domain.name}.{projection_name} v{version.version}")
    if dialect == "postgres":
        lines.append(f"CREATE TABLE IF NOT EXISTS {table_name} (")
        lines.append(",\n".join([*columns, *checks]))
        lines.append(");")
        index_lines, index_warnings = _emit_secondary_index_ddl(version, table_name, mdl)
        lines.extend(index_lines)
        warnings.extend(index_warnings)
    else:
        lines.append(f"CREATE TABLE IF NOT EXISTS {table_name}")
        lines.append("(")
        lines.append(",\n".join(columns))
        lines.append(") ENGINE = MergeTree()")
        lines.append("ORDER BY tuple(); -- TODO: set ORDER BY for production use")

    text = "\n".join(lines) + "\n"
    return EmittedArtifact(
        target=f"sql-{dialect}",
        ref=f"{domain.name}.{projection_name}@{version.version}",
        artifact_id=artifact_id,
        path=out_dir / f"{artifact_id}.sql",
        content=text,
        content_hash=compute_content_hash(text),
        warnings=warnings,
    )


def _resolve_table_name(version: ProjectionVersion, mdl: MdlFile, dialect: str) -> str | None:
    """Return the table name from a matching binding, if one exists."""
    src_model = version.source.model
    adapter_types: dict[str, str] = {b.name: b.adapter for b in mdl.bindings if b.adapter}
    for b in mdl.bindings:
        if not b.model or not b.table:
            continue
        resolved = adapter_types.get(b.adapter, b.adapter)
        if resolved == dialect and b.model == src_model:
            return b.table
    return None


def _emit_secondary_index_ddl(version: ProjectionVersion, table_name: str, mdl: MdlFile) -> tuple[list[str], list[str]]:
    """Render CREATE INDEX statements for the model version's `index` declaration, if any.

    Index field names reference the source *model*, not this projection —
    each is resolved through this projection's DirectMapping fields to its
    own column name. A referenced field the projection doesn't include is
    skipped (with a warning) rather than emitted as a broken column
    reference.
    """
    lines: list[str] = []
    warnings: list[str] = []
    try:
        source_domain, source_model = version.source.model.rsplit(".", 1)
    except ValueError:
        return lines, warnings
    domain_def = next((d for d in mdl.domains if d.name == source_domain), None)
    if domain_def is None:
        return lines, warnings
    try:
        resolved = resolve_model_ref(mdl, f"{source_domain}.{source_model}", version.source.version)
    except LookupError:
        return lines, warnings
    index_decl = next(
        (
            decl
            for decl in domain_def.index_decls
            if decl.model == source_model and decl.version == resolved.version.version
        ),
        None,
    )
    if index_decl is None:
        return lines, warnings

    for secondary in index_decl.secondary:
        columns: list[str] = []
        skipped = False
        for field_name in secondary.key:
            column = _resolve_projection_column(field_name, version)
            if column is None:
                warnings.append(type_loss(f"secondary index '{secondary.name}': field '{field_name}' is not projected"))
                skipped = True
                break
            columns.append(column)
        if skipped:
            continue
        for sort_field in secondary.sort:
            column = _resolve_projection_column(sort_field.field, version)
            if column is None:
                warnings.append(
                    type_loss(f"secondary index '{secondary.name}': field '{sort_field.field}' is not projected")
                )
                skipped = True
                break
            columns.append(f"{column} DESC" if sort_field.direction == "desc" else column)
        if skipped or not columns:
            continue

        keyword = "UNIQUE INDEX" if secondary.unique else "INDEX"
        index_name = _snake_case(secondary.name)
        lines.append(f"CREATE {keyword} IF NOT EXISTS {index_name} ON {table_name} ({', '.join(columns)});")

    return lines, warnings


def _resolve_projection_column(source_field_name: str, version: ProjectionVersion) -> str | None:
    for field in version.fields:
        if isinstance(field.mapping, DirectMapping) and field.mapping.source_field == source_field_name:
            return _snake_case(field.name)
    return None


def _resolve_source_field(field, version: ProjectionVersion, mdl: MdlFile):
    """Return the source FieldDef for a direct-mapped projection field, or None."""
    if not isinstance(field.mapping, DirectMapping):
        return None
    try:
        source_domain, source_model = version.source.model.rsplit(".", 1)
        resolved = resolve_model_ref(mdl, f"{source_domain}.{source_model}", version.source.version)
    except ValueError, LookupError:
        return None
    for src_field in resolved.version.fields:
        if src_field.name == field.mapping.source_field:
            return src_field
    return None


def _resolve_field_type(field, version: ProjectionVersion, mdl: MdlFile):
    """Resolve the source field type for a projection field."""
    src = _resolve_source_field(field, version, mdl)
    return src.type if src is not None else None


def _resolve_merged_wire(field, version: ProjectionVersion, mdl: MdlFile) -> dict:
    """Merge wire targets from the projection field and its source entity field.

    Projection-field annotations take precedence over source-field annotations
    for any target that both define.
    """
    src = _resolve_source_field(field, version, mdl)
    src_wire = src.wire_targets() if src is not None else {}
    proj_wire = field.wire_targets()
    return {**src_wire, **proj_wire}


def _is_optional(field, version: ProjectionVersion, mdl: MdlFile) -> bool:
    src = _resolve_source_field(field, version, mdl)
    if src is None:
        return True
    return src.optional


# ---------------------------------------------------------------------------
# Postgres type mapping
# ---------------------------------------------------------------------------

_PG_PRIMITIVE: dict[str, str] = {
    "string": "TEXT",
    "int": "BIGINT",
    "float": "DOUBLE PRECISION",
    "bool": "BOOLEAN",
    "date": "DATE",
    "time": "TIME",
    "timestamp": "TIMESTAMPTZ",
    "uuid": "UUID",
    "duration": "INTERVAL",
    "binary": "BYTEA",
    "u8": "SMALLINT",
    "u16": "INTEGER",
    "u32": "BIGINT",
    "u64": "NUMERIC(20, 0)",
    "u128": "NUMERIC(39, 0)",
    "i8": "SMALLINT",
    "i16": "SMALLINT",
    "i32": "INTEGER",
    "i64": "BIGINT",
    "i128": "NUMERIC(39, 0)",
}

_PG_UNSIGNED_KINDS = frozenset({"u8", "u16", "u32", "u64", "u128"})


def _pg_base_type(field_type, wire: dict) -> str:
    pg_hint = wire.get("postgres")
    if pg_hint and getattr(pg_hint, "type", None):
        return pg_hint.type
    if isinstance(field_type, PrimitiveType):
        rust_hint = wire.get("rust")
        if rust_hint and getattr(rust_hint, "type", None) == "u64":
            return "BIGINT"
        return _PG_PRIMITIVE.get(field_type.kind, "TEXT")
    if isinstance(field_type, DecimalType):
        return f"NUMERIC({field_type.precision}, {field_type.scale})"
    if isinstance(field_type, FixedBinaryType):
        return "BYTEA"
    if isinstance(field_type, ArrayType):
        element = _pg_base_type(field_type.item, {})
        return f"{element}[]"
    if isinstance(field_type, (MapType, ObjectType)):
        return "JSONB"
    if isinstance(field_type, EnumType):
        return "TEXT"
    if isinstance(field_type, RefType):
        return "TEXT"
    if isinstance(field_type, NamedType):
        return "TEXT"
    return "TEXT"


def _pg_col_type(field_type, wire: dict, *, optional: bool) -> str:
    base = _pg_base_type(field_type, wire)
    return base if optional else f"{base} NOT NULL"


def _pg_needs_unsigned_check(field_type) -> bool:
    return isinstance(field_type, PrimitiveType) and field_type.kind in _PG_UNSIGNED_KINDS


# ---------------------------------------------------------------------------
# ClickHouse type mapping
# ---------------------------------------------------------------------------

_CH_PRIMITIVE: dict[str, str] = {
    "string": "String",
    "int": "Int64",
    "float": "Float64",
    "bool": "Bool",
    "date": "Date",
    "time": "String",
    "timestamp": "DateTime64(9)",
    "uuid": "UUID",
    "duration": "String",
    "binary": "String",
    "u8": "UInt8",
    "u16": "UInt16",
    "u32": "UInt32",
    "u64": "UInt64",
    "u128": "UInt128",
    "i8": "Int8",
    "i16": "Int16",
    "i32": "Int32",
    "i64": "Int64",
    "i128": "Int128",
}


def _ch_base_type(field_type, wire: dict) -> str:
    ch_hint = wire.get("clickhouse")
    if ch_hint:
        encoding = getattr(ch_hint, "encoding", None)
        if encoding == "uuid":
            return "UUID"
        if encoding == "u8":
            return "UInt8"
        if encoding == "string":
            return "String"
    if isinstance(field_type, PrimitiveType):
        rust_hint = wire.get("rust")
        if rust_hint and getattr(rust_hint, "type", None) == "u64":
            return "UInt64"
        return _CH_PRIMITIVE.get(field_type.kind, "String")
    if isinstance(field_type, DecimalType):
        return f"Decimal({field_type.precision}, {field_type.scale})"
    if isinstance(field_type, FixedBinaryType):
        return f"FixedString({field_type.length})"
    if isinstance(field_type, ArrayType):
        element = _ch_base_type(field_type.item, {})
        return f"Array({element})"
    if isinstance(field_type, MapType):
        key = _ch_base_type(field_type.key, {})
        value = _ch_base_type(field_type.value, {})
        return f"Map({key}, {value})"
    if isinstance(field_type, (ObjectType, RefType, NamedType)):
        return "String"
    if isinstance(field_type, EnumType):
        return "LowCardinality(String)"
    return "String"


def _ch_col_type(field_type, wire: dict, *, optional: bool) -> str:
    base = _ch_base_type(field_type, wire)
    return f"Nullable({base})" if optional else base


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _snake_case(value: str) -> str:
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    text = re.sub(r"[^A-Za-z0-9]+", "_", text)
    return text.strip("_").lower() or "generated"
