"""Parser-free SQL projection column rendering for ``modelable.plan/v0``."""

from __future__ import annotations

import re
from pathlib import Path
from typing import Any, cast

from modelable.emitters.base import EmittedArtifact, compute_content_hash
from modelable.emitters.diagnostics import type_loss
from modelable.planner.protocol import PlanDocument, validate_plan

_PG_PRIMITIVE = {
    "string": "TEXT",
    "int": "BIGINT",
    "float": "DOUBLE PRECISION",
    "bool": "BOOLEAN",
    "date": "DATE",
    "time": "TIME",
    "timestamp": "TIMESTAMPTZ",
    "uuid": "UUID",
    "duration": "TEXT",
    "binary": "BYTEA",
    "u8": "SMALLINT",
    "u16": "INTEGER",
    "u32": "BIGINT",
    "u64": "NUMERIC(20, 0)",
    "u128": "NUMERIC(39, 0)",
    "i8": "SMALLINT",
    "i16": "SMALLINT",
    "i32": "INTEGER",
    "i64": "BIGINT",
    "i128": "NUMERIC(39, 0)",
}
_CH_PRIMITIVE = {
    "string": "String",
    "int": "Int64",
    "float": "Float64",
    "bool": "Bool",
    "date": "Date",
    "time": "String",
    "timestamp": "DateTime64(9)",
    "uuid": "UUID",
    "duration": "String",
    "binary": "String",
    "u8": "UInt8",
    "u16": "UInt16",
    "u32": "UInt32",
    "u64": "UInt64",
    "u128": "UInt128",
    "i8": "Int8",
    "i16": "Int16",
    "i32": "Int32",
    "i64": "Int64",
    "i128": "Int128",
}
_PG_UNSIGNED = {"u8", "u16", "u32", "u64", "u128"}


def emit_sql_projection_plan(
    plan: PlanDocument,
    out_dir: Path,
    dialect: str,
    *,
    table_name: str | None = None,
    column_names: dict[str, str] | None = None,
    primary_key_columns: list[str] | None = None,
    wire_by_field: dict[str, dict[str, Any]] | None = None,
) -> EmittedArtifact:
    """Emit a projection table from a validated plan and target-neutral facts."""
    document = validate_plan(plan)
    domain = _string(document, "domain")
    projection = _string(document, "projection")
    version = _integer(document, "version")
    if dialect not in {"postgres", "clickhouse"}:
        raise ValueError(f"unsupported SQL dialect: {dialect!r}")
    names = column_names or {field["name"]: _snake_case(field["name"]) for field in _fields(document)}
    columns, checks, warnings = render_sql_projection_columns(document, dialect, names, wire_by_field)
    table = table_name or _snake_case(projection)
    lines = ["-- @generated by Modelable", f"-- {domain}.{projection} v{version}"]
    if dialect == "postgres":
        keys = primary_key_columns or _plan_key_columns(document, names)
        constraints: list[str] = []
        if len(keys) == 1:
            columns = [
                f"{column} PRIMARY KEY" if column.lstrip().startswith(f"{keys[0]} ") else column for column in columns
            ]
        elif len(keys) > 1:
            constraints.append(f"    PRIMARY KEY ({', '.join(keys)})")
        lines.extend([f"CREATE TABLE IF NOT EXISTS {table} (", ",\n".join([*columns, *checks, *constraints]), ");"])
    else:
        lines.extend([f"CREATE TABLE IF NOT EXISTS {table}", "(", ",\n".join(columns), ") ENGINE = MergeTree()"])
        lines.append("ORDER BY tuple(); -- TODO: set ORDER BY for production use")
    text = "\n".join(lines) + "\n"
    return EmittedArtifact(
        target=f"sql-{dialect}",
        ref=f"{domain}.{projection}@{version}",
        artifact_id=f"{domain}.{projection}.v{version}",
        path=out_dir / f"{domain}.{projection}.v{version}.sql",
        content=text,
        content_hash=compute_content_hash(text),
        warnings=warnings,
    )


def render_sql_projection_columns(
    plan: PlanDocument,
    dialect: str,
    column_names: dict[str, str],
    wire_by_field: dict[str, dict[str, Any]] | None = None,
) -> tuple[list[str], list[str], list[str]]:
    """Render column, check, and diagnostic fragments from plan facts."""
    document = validate_plan(plan)
    domain = _string(document, "domain")
    projection = _string(document, "projection")
    columns: list[str] = []
    checks: list[str] = []
    warnings: list[str] = []
    for field in _fields(document):
        name = _string(field, "name")
        field_type = _source_or_field_type(document, field)
        column = column_names.get(name, _snake_case(name))
        wire = (wire_by_field or {}).get(name, {})
        optional = field.get("optional") is not False
        if field_type is None:
            warnings.append(type_loss(f"{domain}.{projection}.{name}"))
            col_type = "TEXT" if dialect == "postgres" else "String"
        elif dialect == "postgres":
            col_type = _pg_col_type(field_type, wire, optional)
            if field_type.get("kind") in _PG_UNSIGNED:
                checks.append(f"    CHECK ({column} >= 0)")
            if field_type.get("kind") == "fixed_binary":
                checks.append(f"    CHECK (octet_length({column}) = {field_type.get('length')})")
        else:
            col_type = _ch_col_type(field_type, wire, optional)
        columns.append(f"    {column} {col_type}")
    return columns, checks, warnings


def _source_or_field_type(plan: PlanDocument, field: dict[str, Any]) -> dict[str, Any] | None:
    if field.get("kind") != "direct":
        value = field.get("type")
        return cast(dict[str, Any], value) if isinstance(value, dict) else None
    alias = field.get("source_alias")
    source_name = field.get("source_field")
    for relation in [_mapping(plan, "source"), *_mappings(plan.get("joins"))]:
        if relation.get("alias") != alias:
            continue
        resolved = relation.get("resolved")
        if isinstance(resolved, dict):
            for source in resolved.get("fields", []):
                if isinstance(source, dict) and source.get("name") == source_name:
                    value = source.get("type")
                    return cast(dict[str, Any], value) if isinstance(value, dict) else None
    value = field.get("type")
    return cast(dict[str, Any], value) if isinstance(value, dict) else None


def _pg_col_type(field_type: dict[str, Any], wire: dict[str, Any], optional: bool) -> str:
    base = _pg_base_type(field_type, wire)
    return base if optional else f"{base} NOT NULL"


def _pg_base_type(field_type: dict[str, Any], wire: dict[str, Any]) -> str:
    hint = _hint(wire.get("postgres"), "type")
    if hint:
        return hint
    kind = field_type.get("kind")
    if kind == "decimal":
        return f"NUMERIC({field_type.get('precision')}, {field_type.get('scale')})"
    if kind == "fixed_binary":
        return "BYTEA"
    if kind == "array":
        return f"{_pg_base_type(_mapping(field_type, 'item'), {})}[]"
    if kind in {"map", "object", "union"}:
        return "JSONB"
    if kind == "enum":
        return "TEXT"
    if kind == "named":
        return "JSONB" if _mapping(field_type, "resolved_model").get("model_kind") == "value" else "TEXT"
    return _PG_PRIMITIVE.get(str(kind), "TEXT")


def _ch_col_type(field_type: dict[str, Any], wire: dict[str, Any], optional: bool) -> str:
    base = _ch_base_type(field_type, wire)
    if optional and field_type.get("kind") == "array":
        return base
    return f"Nullable({base})" if optional else base


def _ch_base_type(field_type: dict[str, Any], wire: dict[str, Any]) -> str:
    hint = _hint(wire.get("clickhouse"), "encoding")
    if hint == "uuid":
        return "UUID"
    if hint == "u8":
        return "UInt8"
    if hint == "string":
        return "String"
    if _hint(wire.get("rust"), "type") == "u64":
        return "UInt64"
    kind = field_type.get("kind")
    if kind == "decimal":
        return f"Decimal({field_type.get('precision')}, {field_type.get('scale')})"
    if kind == "fixed_binary":
        return f"FixedString({field_type.get('length')})"
    if kind == "array":
        return f"Array({_ch_base_type(_mapping(field_type, 'item'), {})})"
    if kind == "map":
        return (
            f"Map({_ch_base_type(_mapping(field_type, 'key'), {})}, {_ch_base_type(_mapping(field_type, 'value'), {})})"
        )
    if kind == "enum":
        return "LowCardinality(String)"
    return _CH_PRIMITIVE.get(str(kind), "String")


def _plan_key_columns(plan: PlanDocument, names: dict[str, str]) -> list[str]:
    source = _mapping(plan, "source")
    resolved = source.get("resolved")
    if not isinstance(resolved, dict):
        return []
    keys = {
        _string(field, "name")
        for field in resolved.get("fields", [])
        if isinstance(field, dict)
        and any(
            isinstance(annotation, dict) and annotation.get("kind") == "key"
            for annotation in field.get("annotations", [])
        )
    }
    return [
        names[field["source_field"]]
        for field in _fields(plan)
        if field.get("kind") == "direct" and field.get("source_field") in keys
    ]


def _mapping(mapping: dict[str, object], key: str) -> dict[str, Any]:
    value = mapping.get(key)
    return cast(dict[str, Any], value) if isinstance(value, dict) else {}


def _mappings(value: object) -> list[dict[str, Any]]:
    return [cast(dict[str, Any], item) for item in value if isinstance(item, dict)] if isinstance(value, list) else []


def _fields(plan: dict[str, object]) -> list[dict[str, Any]]:
    return _mappings(plan.get("fields"))


def _string(mapping: dict[str, object], key: str) -> str:
    return str(mapping.get(key, ""))


def _integer(mapping: dict[str, object], key: str) -> int:
    value = mapping.get(key)
    if not isinstance(value, int):
        raise TypeError(f"{key} must be an integer")
    return value


def _hint(value: object, key: str) -> str | None:
    candidate = value.get(key) if isinstance(value, dict) else getattr(value, key, None)
    return candidate if isinstance(candidate, str) else None


def _snake_case(value: str) -> str:
    text = re.sub(r"([a-z0-9])([A-Z])", r"\1_\2", value)
    text = re.sub(r"[^A-Za-z0-9]+", "_", text)
    return text.strip("_").lower() or "generated"
