// @generated by Modelable
// requires: chrono (https://docs.rs/chrono)
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerV1 {
    #[serde(rename = "customerId")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "displayName")]
    pub display_name: String,
    pub email: String,
    pub status: CustomerCustomerV1Status,
    pub tags: Vec<String>,
    pub metadata: HashMap<String, i64>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(rename = "internalRiskNotes")]
    pub internal_risk_notes: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    pub address: Option<CustomerCustomerV1Address>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(rename = "favoriteProduct")]
    pub favorite_product: Option<String>,
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(default)]
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

impl CustomerCustomerV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0x13, 0xe2, 0x79, 0x86, 0xc8, 0x6e, 0xfd, 0x2e,
        0xc2, 0x9e, 0xc8, 0x3d, 0xe2, 0xc1, 0xc7, 0x25,
        0xdc, 0xd6, 0x54, 0xea, 0xad, 0x29, 0xb6, 0x0b,
        0x5e, 0xa3, 0xad, 0x9f, 0x74, 0x28, 0x4f, 0x51,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CustomerCustomerV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "deleted")]
    Deleted,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerV1Address {
    pub line1: String,
    #[serde(default)]
    pub line2: Option<String>,
}
