// @generated by Modelable
// requires: chrono (https://docs.rs/chrono)
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerEventV1 {
    #[serde(rename = "customerId")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "displayName")]
    pub display_name: String,
    pub email: String,
    pub status: CustomerCustomerEventV1Status,
    pub tags: Vec<String>,
    pub metadata: HashMap<String, i64>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "internalRiskNotes")]
    pub internal_risk_notes: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<CustomerCustomerEventV1Address>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "favoriteProduct")]
    pub favorite_product: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

impl CustomerCustomerEventV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0x23, 0xc2, 0x9a, 0xa7, 0xcb, 0xca, 0x0c, 0xfa,
        0x61, 0xc1, 0xec, 0xab, 0x85, 0x77, 0x81, 0xe9,
        0x63, 0xe0, 0xa8, 0x51, 0x24, 0xb0, 0x8c, 0xb0,
        0x06, 0x65, 0x0d, 0x0f, 0x8e, 0x9f, 0x15, 0xe3,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CustomerCustomerEventV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "deleted")]
    Deleted,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerEventV1Address {
    pub line1: String,
    #[serde(default)]
    pub line2: Option<String>,
}

use super::customer_customer_v1::CustomerCustomerV1;
#[allow(clippy::useless_conversion)]
impl From<CustomerCustomerV1> for CustomerCustomerEventV1 {
    fn from(src: CustomerCustomerV1) -> Self {
        Self {
            customer_id: src.customer_id.into(),
            display_name: src.display_name.into(),
            email: src.email.into(),
            internal_risk_notes: src.internal_risk_notes.into(),
            status: src.status.into(),
            tags: src.tags.into(),
            metadata: src.metadata.into(),
            address: Default::default(), // nested struct — provide manual impl
            favorite_product: src.favorite_product.into(),
            created_at: src.created_at.into(),
            updated_at: src.updated_at.into(),
        }
    }
}

use super::customer_customer_v1::CustomerCustomerV1Status;
impl From<CustomerCustomerV1Status> for CustomerCustomerEventV1Status {
    fn from(src: CustomerCustomerV1Status) -> Self {
        match src {
            CustomerCustomerV1Status::Active => CustomerCustomerEventV1Status::Active,
            CustomerCustomerV1Status::Deleted => CustomerCustomerEventV1Status::Deleted,
            CustomerCustomerV1Status::Suspended => CustomerCustomerEventV1Status::Suspended,
        }
    }
}

use super::customer_customer_db_v1::CustomerCustomerDbV1Status;
impl From<CustomerCustomerDbV1Status> for CustomerCustomerEventV1Status {
    fn from(src: CustomerCustomerDbV1Status) -> Self {
        match src {
            CustomerCustomerDbV1Status::Active => CustomerCustomerEventV1Status::Active,
            CustomerCustomerDbV1Status::Deleted => CustomerCustomerEventV1Status::Deleted,
            CustomerCustomerDbV1Status::Suspended => CustomerCustomerEventV1Status::Suspended,
        }
    }
}

use super::customer_customer_request_v1::CustomerCustomerRequestV1Status;
impl From<CustomerCustomerRequestV1Status> for CustomerCustomerEventV1Status {
    fn from(src: CustomerCustomerRequestV1Status) -> Self {
        match src {
            CustomerCustomerRequestV1Status::Active => CustomerCustomerEventV1Status::Active,
            CustomerCustomerRequestV1Status::Deleted => CustomerCustomerEventV1Status::Deleted,
            CustomerCustomerRequestV1Status::Suspended => CustomerCustomerEventV1Status::Suspended,
        }
    }
}

use super::customer_customer_reply_v1::CustomerCustomerReplyV1Status;
impl From<CustomerCustomerReplyV1Status> for CustomerCustomerEventV1Status {
    fn from(src: CustomerCustomerReplyV1Status) -> Self {
        match src {
            CustomerCustomerReplyV1Status::Active => CustomerCustomerEventV1Status::Active,
            CustomerCustomerReplyV1Status::Deleted => CustomerCustomerEventV1Status::Deleted,
            CustomerCustomerReplyV1Status::Suspended => CustomerCustomerEventV1Status::Suspended,
        }
    }
}
