// @generated by Modelable
// requires: chrono (https://docs.rs/chrono)
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerDbV1 {
    #[serde(rename = "customerId")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "displayName")]
    pub display_name: String,
    pub email: String,
    pub status: CustomerCustomerDbV1Status,
    pub tags: Vec<String>,
    pub metadata: HashMap<String, i64>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "internalRiskNotes")]
    pub internal_risk_notes: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<CustomerCustomerDbV1Address>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "favoriteProduct")]
    pub favorite_product: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

impl CustomerCustomerDbV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0xf6, 0x87, 0x67, 0x53, 0x57, 0x49, 0xa3, 0xe3,
        0x82, 0x4f, 0x2e, 0xf5, 0x40, 0x6b, 0xd2, 0x47,
        0xdc, 0x16, 0x89, 0x79, 0x59, 0xd6, 0x10, 0xe5,
        0xc4, 0x05, 0xfc, 0x30, 0x82, 0xbb, 0x6c, 0x65,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CustomerCustomerDbV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "deleted")]
    Deleted,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerDbV1Address {
    pub line1: String,
    #[serde(default)]
    pub line2: Option<String>,
}

use super::customer_customer_v1::CustomerCustomerV1;
#[allow(clippy::useless_conversion)]
impl From<CustomerCustomerV1> for CustomerCustomerDbV1 {
    fn from(src: CustomerCustomerV1) -> Self {
        Self {
            customer_id: src.customer_id.into(),
            display_name: src.display_name.into(),
            email: src.email.into(),
            internal_risk_notes: src.internal_risk_notes.into(),
            status: src.status.into(),
            tags: src.tags.into(),
            metadata: src.metadata.into(),
            address: Default::default(), // nested struct — provide manual impl
            favorite_product: src.favorite_product.into(),
            created_at: src.created_at.into(),
            updated_at: src.updated_at.into(),
        }
    }
}

use super::customer_customer_v1::CustomerCustomerV1Status;
impl From<CustomerCustomerV1Status> for CustomerCustomerDbV1Status {
    fn from(src: CustomerCustomerV1Status) -> Self {
        match src {
            CustomerCustomerV1Status::Active => CustomerCustomerDbV1Status::Active,
            CustomerCustomerV1Status::Deleted => CustomerCustomerDbV1Status::Deleted,
            CustomerCustomerV1Status::Suspended => CustomerCustomerDbV1Status::Suspended,
        }
    }
}

use super::customer_customer_request_v1::CustomerCustomerRequestV1Status;
impl From<CustomerCustomerRequestV1Status> for CustomerCustomerDbV1Status {
    fn from(src: CustomerCustomerRequestV1Status) -> Self {
        match src {
            CustomerCustomerRequestV1Status::Active => CustomerCustomerDbV1Status::Active,
            CustomerCustomerRequestV1Status::Deleted => CustomerCustomerDbV1Status::Deleted,
            CustomerCustomerRequestV1Status::Suspended => CustomerCustomerDbV1Status::Suspended,
        }
    }
}

use super::customer_customer_reply_v1::CustomerCustomerReplyV1Status;
impl From<CustomerCustomerReplyV1Status> for CustomerCustomerDbV1Status {
    fn from(src: CustomerCustomerReplyV1Status) -> Self {
        match src {
            CustomerCustomerReplyV1Status::Active => CustomerCustomerDbV1Status::Active,
            CustomerCustomerReplyV1Status::Deleted => CustomerCustomerDbV1Status::Deleted,
            CustomerCustomerReplyV1Status::Suspended => CustomerCustomerDbV1Status::Suspended,
        }
    }
}

use super::customer_customer_event_v1::CustomerCustomerEventV1Status;
impl From<CustomerCustomerEventV1Status> for CustomerCustomerDbV1Status {
    fn from(src: CustomerCustomerEventV1Status) -> Self {
        match src {
            CustomerCustomerEventV1Status::Active => CustomerCustomerDbV1Status::Active,
            CustomerCustomerEventV1Status::Deleted => CustomerCustomerDbV1Status::Deleted,
            CustomerCustomerEventV1Status::Suspended => CustomerCustomerDbV1Status::Suspended,
        }
    }
}
