// @generated by Modelable
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerRequestV1 {
    #[serde(rename = "customerId")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "displayName")]
    pub display_name: String,
    pub email: String,
    pub status: CustomerCustomerRequestV1Status,
    pub tags: Vec<String>,
    pub metadata: HashMap<String, i64>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<CustomerCustomerRequestV1Address>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "favoriteProduct")]
    pub favorite_product: Option<String>,
}

impl CustomerCustomerRequestV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0xd9, 0x2a, 0xfc, 0x25, 0xfb, 0x64, 0x4b, 0x65,
        0x96, 0x4b, 0xef, 0xb7, 0x25, 0x23, 0x22, 0x9f,
        0x73, 0x35, 0x44, 0x4b, 0x17, 0x3e, 0xfa, 0xbe,
        0x97, 0xfe, 0x0e, 0x20, 0x83, 0x59, 0x7f, 0x3a,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CustomerCustomerRequestV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "deleted")]
    Deleted,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerRequestV1Address {
    pub line1: String,
    #[serde(default)]
    pub line2: Option<String>,
}

use super::customer_customer_v1::CustomerCustomerV1;
#[allow(clippy::useless_conversion)]
impl From<CustomerCustomerV1> for CustomerCustomerRequestV1 {
    fn from(src: CustomerCustomerV1) -> Self {
        Self {
            customer_id: src.customer_id.into(),
            display_name: src.display_name.into(),
            email: src.email.into(),
            status: src.status.into(),
            tags: src.tags.into(),
            metadata: src.metadata.into(),
            address: Default::default(), // nested struct — provide manual impl
            favorite_product: src.favorite_product.into(),
        }
    }
}

use super::customer_customer_v1::CustomerCustomerV1Status;
impl From<CustomerCustomerV1Status> for CustomerCustomerRequestV1Status {
    fn from(src: CustomerCustomerV1Status) -> Self {
        match src {
            CustomerCustomerV1Status::Active => CustomerCustomerRequestV1Status::Active,
            CustomerCustomerV1Status::Deleted => CustomerCustomerRequestV1Status::Deleted,
            CustomerCustomerV1Status::Suspended => CustomerCustomerRequestV1Status::Suspended,
        }
    }
}

use super::customer_customer_db_v1::CustomerCustomerDbV1Status;
impl From<CustomerCustomerDbV1Status> for CustomerCustomerRequestV1Status {
    fn from(src: CustomerCustomerDbV1Status) -> Self {
        match src {
            CustomerCustomerDbV1Status::Active => CustomerCustomerRequestV1Status::Active,
            CustomerCustomerDbV1Status::Deleted => CustomerCustomerRequestV1Status::Deleted,
            CustomerCustomerDbV1Status::Suspended => CustomerCustomerRequestV1Status::Suspended,
        }
    }
}

use super::customer_customer_reply_v1::CustomerCustomerReplyV1Status;
impl From<CustomerCustomerReplyV1Status> for CustomerCustomerRequestV1Status {
    fn from(src: CustomerCustomerReplyV1Status) -> Self {
        match src {
            CustomerCustomerReplyV1Status::Active => CustomerCustomerRequestV1Status::Active,
            CustomerCustomerReplyV1Status::Deleted => CustomerCustomerRequestV1Status::Deleted,
            CustomerCustomerReplyV1Status::Suspended => CustomerCustomerRequestV1Status::Suspended,
        }
    }
}

use super::customer_customer_event_v1::CustomerCustomerEventV1Status;
impl From<CustomerCustomerEventV1Status> for CustomerCustomerRequestV1Status {
    fn from(src: CustomerCustomerEventV1Status) -> Self {
        match src {
            CustomerCustomerEventV1Status::Active => CustomerCustomerRequestV1Status::Active,
            CustomerCustomerEventV1Status::Deleted => CustomerCustomerRequestV1Status::Deleted,
            CustomerCustomerEventV1Status::Suspended => CustomerCustomerRequestV1Status::Suspended,
        }
    }
}
