// @generated by Modelable
// requires: chrono (https://docs.rs/chrono)
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerReplyV1 {
    #[serde(rename = "customerId")]
    pub customer_id: uuid::Uuid,
    #[serde(rename = "displayName")]
    pub display_name: String,
    pub status: CustomerCustomerReplyV1Status,
    pub tags: Vec<String>,
    pub metadata: HashMap<String, i64>,
    #[serde(rename = "createdAt")]
    pub created_at: chrono::DateTime<chrono::Utc>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    pub address: Option<CustomerCustomerReplyV1Address>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "favoriteProduct")]
    pub favorite_product: Option<String>,
    #[serde(default)]
    #[serde(skip_serializing_if = "Option::is_none")]
    #[serde(rename = "updatedAt")]
    pub updated_at: Option<chrono::DateTime<chrono::Utc>>,
}

impl CustomerCustomerReplyV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0xd0, 0xee, 0x4d, 0x47, 0xdc, 0x5e, 0x7d, 0xc2,
        0x5a, 0x1e, 0xc8, 0xec, 0x2a, 0xe1, 0x2f, 0x3b,
        0x08, 0xe3, 0xee, 0xb1, 0xa7, 0xc2, 0xbb, 0x6c,
        0x9f, 0x9e, 0xf5, 0xea, 0x06, 0x5f, 0x55, 0xeb,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum CustomerCustomerReplyV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "suspended")]
    Suspended,
    #[serde(rename = "deleted")]
    Deleted,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CustomerCustomerReplyV1Address {
    pub line1: String,
    #[serde(default)]
    pub line2: Option<String>,
}

use super::customer_customer_v1::CustomerCustomerV1;
#[allow(clippy::useless_conversion)]
impl From<CustomerCustomerV1> for CustomerCustomerReplyV1 {
    fn from(src: CustomerCustomerV1) -> Self {
        Self {
            customer_id: src.customer_id.into(),
            display_name: src.display_name.into(),
            status: src.status.into(),
            tags: src.tags.into(),
            metadata: src.metadata.into(),
            address: Default::default(), // nested struct — provide manual impl
            favorite_product: src.favorite_product.into(),
            created_at: src.created_at.into(),
            updated_at: src.updated_at.into(),
        }
    }
}

use super::customer_customer_v1::CustomerCustomerV1Status;
impl From<CustomerCustomerV1Status> for CustomerCustomerReplyV1Status {
    fn from(src: CustomerCustomerV1Status) -> Self {
        match src {
            CustomerCustomerV1Status::Active => CustomerCustomerReplyV1Status::Active,
            CustomerCustomerV1Status::Suspended => CustomerCustomerReplyV1Status::Suspended,
            CustomerCustomerV1Status::Deleted => CustomerCustomerReplyV1Status::Deleted,
        }
    }
}
