-- @generated by Modelable
-- customer.CustomerRequest v1
CREATE TABLE IF NOT EXISTS customer_request (
    customer_id UUID NOT NULL PRIMARY KEY,
    display_name TEXT NOT NULL,
    email TEXT NOT NULL,
    status TEXT NOT NULL,
    tags TEXT[] NOT NULL,
    metadata JSONB NOT NULL,
    address JSONB,
    favorite_product TEXT,
    FOREIGN KEY (favorite_product) REFERENCES product_db (product_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS customer_request_by_email ON customer_request (email);
CREATE INDEX IF NOT EXISTS customer_request_by_status ON customer_request (status);
