-- @generated by Modelable
-- customer.CustomerDb v1
CREATE TABLE IF NOT EXISTS customer_db (
    customer_id UUID NOT NULL PRIMARY KEY,
    display_name TEXT NOT NULL,
    email TEXT NOT NULL,
    internal_risk_notes TEXT,
    status TEXT NOT NULL,
    tags TEXT[] NOT NULL,
    metadata JSONB NOT NULL,
    address JSONB,
    favorite_product TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (favorite_product) REFERENCES product_db (product_id)
);
CREATE UNIQUE INDEX IF NOT EXISTS customer_db_by_email ON customer_db (email);
CREATE INDEX IF NOT EXISTS customer_db_by_status ON customer_db (status);
