-- @generated by Modelable
-- customer.CustomerReply v1
CREATE TABLE IF NOT EXISTS customer_reply (
    customer_id UUID NOT NULL PRIMARY KEY,
    display_name TEXT NOT NULL,
    status TEXT NOT NULL,
    tags TEXT[] NOT NULL,
    metadata JSONB NOT NULL,
    address JSONB,
    favorite_product TEXT,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ,
    FOREIGN KEY (favorite_product) REFERENCES product_db (product_id)
);
CREATE INDEX IF NOT EXISTS customer_reply_by_status ON customer_reply (status);
