version: 2
updates:
  - package-ecosystem: pip
    directory: /cli
    schedule:
      interval: weekly
      day: monday
    groups:
      python-dependencies:
        applies-to: version-updates
        patterns: ["*"]

  - package-ecosystem: npm
    directory: /vscode
    schedule:
      interval: weekly
      day: monday
    groups:
      vscode-dependencies:
        applies-to: version-updates
        patterns: ["*"]

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
    groups:
      actions:
        applies-to: version-updates
        patterns: ["*"]
