from __future__ import annotations

import yaml

from modelable.compiler.workspace import load_workspace
from modelable.emitters.dbt_yaml import emit_dbt_yaml


def test_emit_dbt_yaml_model_and_projection(tmp_path):
    (tmp_path / "customer.mdl").write_text(
        """
domain customer {
  owner: "customer-team"
  contact: "customer-team@example.com"
  description: "Manage customers and accounts"

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    @pii @classification("restricted") name: string
    age?: int
    joinedAt: timestamp
  }

  projection CustomerSummary @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    name <- c.name
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_dbt_yaml(workspace, tmp_path / "out")

    # Verify model artifact
    art_model = next(a for a in artifacts if a.ref == "customer.Customer@1")
    assert art_model.target == "dbt-yaml"
    assert art_model.artifact_id == "customer.Customer.v1"

    # Parse the yaml
    doc_model = yaml.safe_load(art_model.content.replace("# @generated by Modelable\n", ""))
    assert doc_model["version"] == 2
    assert len(doc_model["models"]) == 1

    model_entry = doc_model["models"][0]
    assert model_entry["name"] == "Customer"
    assert model_entry["latest_version"] == 1
    assert model_entry["description"] == "Manage customers and accounts"

    # Model meta
    meta = model_entry["meta"]
    assert meta["modelable_domain"] == "customer"
    assert meta["modelable_name"] == "Customer"
    assert meta["modelable_kind"] == "entity"
    assert meta["modelable_version"] == 1
    assert meta["modelable_change_kind"] == "additive"
    assert meta["modelable_owner"] == "customer-team"
    assert meta["modelable_contact"] == "customer-team@example.com"

    # Model versions columns
    assert len(model_entry["versions"]) == 1
    version_entry = model_entry["versions"][0]
    assert version_entry["v"] == 1

    columns = version_entry["columns"]
    assert len(columns) == 4

    # customerId
    col_id = next(c for c in columns if c["name"] == "customerId")
    assert col_id["data_type"] == "uuid"
    assert {"type": "primary_key"} in col_id["constraints"]
    assert {"type": "not_null"} in col_id["constraints"]

    # name
    col_name = next(c for c in columns if c["name"] == "name")
    assert col_name["data_type"] == "text"
    assert col_name["meta"]["modelable_pii"] is True
    assert col_name["meta"]["modelable_classification"] == "restricted"
    assert col_name["meta"]["modelable_owner"] == "customer-team"
    assert {"type": "not_null"} in col_name["constraints"]
    assert "constraints" not in col_name or all(ct["type"] != "primary_key" for ct in col_name["constraints"])

    # age
    col_age = next(c for c in columns if c["name"] == "age")
    assert col_age["data_type"] == "integer"
    assert "constraints" not in col_age or not col_age["constraints"]

    # joinedAt
    col_joined = next(c for c in columns if c["name"] == "joinedAt")
    assert col_joined["data_type"] == "timestamp"
    assert {"type": "not_null"} in col_joined["constraints"]

    # Verify projection artifact
    art_proj = next(a for a in artifacts if a.ref == "customer.CustomerSummary@1")
    assert art_proj.target == "dbt-yaml"
    assert art_proj.artifact_id == "customer.CustomerSummary.v1"

    doc_proj = yaml.safe_load(art_proj.content.replace("# @generated by Modelable\n", ""))
    proj_entry = doc_proj["models"][0]
    assert proj_entry["name"] == "CustomerSummary"
    assert proj_entry["latest_version"] == 1

    proj_meta = proj_entry["meta"]
    assert proj_meta["modelable_domain"] == "customer"
    assert proj_meta["modelable_name"] == "CustomerSummary"
    assert proj_meta["modelable_kind"] == "projection"
    assert proj_meta["modelable_version"] == 1
    assert proj_meta["modelable_source"] == "customer.Customer@1"

    proj_version_entry = proj_entry["versions"][0]
    proj_columns = proj_version_entry["columns"]
    assert len(proj_columns) == 2

    proj_col_id = next(c for c in proj_columns if c["name"] == "customerId")
    assert proj_col_id["data_type"] == "uuid"
    assert proj_col_id["meta"]["modelable_lineage"] == ["customer.Customer@1.customerId"]

    proj_col_name = next(c for c in proj_columns if c["name"] == "name")
    assert proj_col_name["data_type"] == "text"
    assert proj_col_name["meta"]["modelable_lineage"] == ["customer.Customer@1.name"]
