from __future__ import annotations

import yaml
from click.testing import CliRunner

from modelable.cli import cli
from modelable.compiler.workspace import load_workspace
from modelable.emitters.odcs import emit_odcs


def test_emit_odcs_model_and_projection(tmp_path):
    (tmp_path / "customer.mdl").write_text(
        """
domain customer {
  owner: "customer-team"
  contact: "customer-team@example.com"
  description: "Manage customers and accounts"

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    @pii
    @classification("confidential")
    @owner("identity-team")
    email: string
    status: enum(active, blocked)
    joinedAt?: timestamp
  }

  projection CustomerSummary @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    email <- c.email
    status <- c.status
    displayName = c.email
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_odcs(workspace, tmp_path / "out")

    model_art = next(art for art in artifacts if art.ref == "customer.Customer@1")
    assert model_art.target == "odcs"
    assert model_art.artifact_id == "customer.Customer.v1"
    assert model_art.path == tmp_path / "out" / "customer.Customer.v1.odcs.yaml"

    model_doc = yaml.safe_load(model_art.content.replace("# @generated by Modelable\n", ""))
    assert model_doc["apiVersion"] == "v3.1.0"
    assert model_doc["kind"] == "DataContract"
    assert model_doc["id"] == "modelable://customer/Customer/v1"
    assert model_doc["name"] == "customer.Customer.v1"
    assert model_doc["version"] == "1"
    assert model_doc["domain"] == "customer"
    assert model_doc["status"] == "active"
    assert model_doc["description"]["purpose"] == "Manage customers and accounts"
    assert model_doc["customProperties"] == {
        "modelable_ref": "customer.Customer@1",
        "modelable_kind": "entity",
        "modelable_change_kind": "additive",
        "modelable_owner": "customer-team",
        "modelable_contact": "customer-team@example.com",
    }

    schema = model_doc["schema"][0]
    assert schema["name"] == "Customer"
    assert schema["logicalType"] == "object"
    assert schema["physicalName"] == "Customer"

    customer_id = next(prop for prop in schema["properties"] if prop["name"] == "customerId")
    assert customer_id == {
        "name": "customerId",
        "logicalType": "uuid",
        "required": True,
        "primaryKey": True,
        "customProperties": {"modelable_type": "uuid"},
    }

    email = next(prop for prop in schema["properties"] if prop["name"] == "email")
    assert email == {
        "name": "email",
        "logicalType": "string",
        "required": True,
        "pii": True,
        "classificationLevel": "confidential",
        "owner": "identity-team",
        "customProperties": {"modelable_type": "string"},
    }

    status = next(prop for prop in schema["properties"] if prop["name"] == "status")
    assert status == {
        "name": "status",
        "logicalType": "string",
        "required": True,
        "enum": ["active", "blocked"],
        "customProperties": {"modelable_type": "enum(active,blocked)"},
    }

    joined_at = next(prop for prop in schema["properties"] if prop["name"] == "joinedAt")
    assert joined_at["logicalType"] == "timestamp"
    assert joined_at["required"] is False

    projection_art = next(art for art in artifacts if art.ref == "customer.CustomerSummary@1")
    projection_doc = yaml.safe_load(projection_art.content.replace("# @generated by Modelable\n", ""))
    assert projection_doc["customProperties"]["modelable_kind"] == "projection"
    assert projection_doc["customProperties"]["modelable_source"] == "customer.Customer@1"

    projection_fields = projection_doc["schema"][0]["properties"]
    projection_email = next(prop for prop in projection_fields if prop["name"] == "email")
    assert projection_email["logicalType"] == "string"
    assert projection_email["pii"] is True
    assert projection_email["classificationLevel"] == "confidential"
    assert projection_email["customProperties"]["modelable_lineage"] == ["customer.Customer@1.email"]

    display_name = next(prop for prop in projection_fields if prop["name"] == "displayName")
    assert display_name["logicalType"] == "string"
    assert display_name["customProperties"]["modelable_mapping"] == "computed"
    assert display_name["customProperties"]["modelable_expression"] == "c.email"


def test_compile_odcs_writes_yaml_artifact(tmp_path):
    mdl = tmp_path / "customer.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "customer-team"

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    email?: string
  }
}
""",
        encoding="utf-8",
    )

    out = tmp_path / "dist"
    result = CliRunner().invoke(cli, ["compile", str(mdl), "--target", "odcs", "--out", str(out)])

    assert result.exit_code == 0, result.output
    artifact = out / "customer.Customer.v1.odcs.yaml"
    assert artifact.exists()
    doc = yaml.safe_load(artifact.read_text(encoding="utf-8").replace("# @generated by Modelable\n", ""))
    assert doc["apiVersion"] == "v3.1.0"
    assert doc["name"] == "customer.Customer.v1"
