import hashlib

from click.testing import CliRunner

from modelable.cli import cli
from modelable.compiler.workspace import load_workspace
from modelable.emitters.go import emit_go


def test_emit_go_model_and_projection(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    tags: array<string>
    nickname?: string
    attributes?: map<string, int>
    address?: object {
      line1: string
      line2?: string
    }
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName <- c.displayName
    tags <- c.tags
    nickname <- c.nickname
    attributes <- c.attributes
    address <- c.address
  }
}
""",
        encoding="utf-8",
    )

    workspace = load_workspace(tmp_path)
    artifacts = emit_go(workspace, tmp_path / "out")
    refs = {artifact.ref for artifact in artifacts}
    assert "customer.Customer@1" in refs
    assert "customer.CustomerView@1" in refs

    model_art = next(artifact for artifact in artifacts if artifact.ref == "customer.Customer@1")
    assert model_art.content_hash == hashlib.sha256(model_art.content.encode("utf-8")).hexdigest()
    assert model_art.path.as_posix().endswith("customer/customer_customer_v1.go")
    assert "// Code generated by Modelable; DO NOT EDIT." in model_art.content
    assert "package customer" in model_art.content
    assert "type CustomerCustomerV1 struct" in model_art.content
    assert 'CustomerId string `json:"customerId"`' in model_art.content
    assert 'DisplayName string `json:"displayName"`' in model_art.content
    assert 'Tags []string `json:"tags"`' in model_art.content
    assert 'Nickname *string `json:"nickname,omitempty"`' in model_art.content
    assert 'Attributes *map[string]int64 `json:"attributes,omitempty"`' in model_art.content
    assert 'Address *CustomerCustomerV1Address `json:"address,omitempty"`' in model_art.content
    assert "type CustomerCustomerV1Address struct" in model_art.content
    assert 'Line1 string `json:"line1"`' in model_art.content
    assert 'Line2 *string `json:"line2,omitempty"`' in model_art.content

    proj_art = next(artifact for artifact in artifacts if artifact.ref == "customer.CustomerView@1")
    assert proj_art.content_hash == hashlib.sha256(proj_art.content.encode("utf-8")).hexdigest()
    assert proj_art.path.as_posix().endswith("customer/customer_customer_view_v1.go")
    assert "type CustomerCustomerViewV1 struct" in proj_art.content
    assert 'CustomerId string `json:"customerId"`' in proj_art.content
    assert 'DisplayName string `json:"displayName"`' in proj_art.content
    assert 'Tags []string `json:"tags"`' in proj_art.content
    assert 'Nickname *string `json:"nickname,omitempty"`' in proj_art.content
    assert 'Attributes *map[string]int64 `json:"attributes,omitempty"`' in proj_art.content
    assert 'Address *CustomerCustomerViewV1Address `json:"address,omitempty"`' in proj_art.content
    assert "type CustomerCustomerViewV1Address struct" in proj_art.content


def test_cli_compile_go_writes_files(tmp_path):
    mdl = tmp_path / "customer.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    nickname?: string
  }
}
""",
        encoding="utf-8",
    )

    out = tmp_path / "dist" / "go"
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path):
        result = runner.invoke(
            cli,
            ["compile", str(mdl), "--target", "go", "--out", str(out)],
        )

    assert result.exit_code == 0, result.output
    assert (out / "customer" / "customer_customer_v1.go").exists()
    assert any(
        len(part) == 64 and all(ch in "0123456789abcdef" for ch in part.lower()) for part in result.output.split()
    )
    text = (out / "customer" / "customer_customer_v1.go").read_text(encoding="utf-8")
    assert "type CustomerCustomerV1 struct" in text
    assert 'CustomerId string `json:"customerId"`' in text
    assert 'Nickname *string `json:"nickname,omitempty"`' in text


def test_emit_go_warns_on_computed_projection_field(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName = c.name + "!"
  }
}
""",
        encoding="utf-8",
    )
    from modelable.compiler.workspace import load_workspace

    workspace = load_workspace(tmp_path)
    artifacts = emit_go(workspace, tmp_path / "out")
    proj_art = next(a for a in artifacts if a.ref == "customer.CustomerView@1")
    assert proj_art.warnings
    assert any("EMIT002" in w for w in proj_art.warnings)


def test_emit_go_decimal_maps_to_string(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain finance {
  owner: "test-team"
  entity Invoice @ 1 (additive) {
    @key invoiceId: uuid
    amount: decimal(12, 2)
    taxRate?: decimal(5, 4)
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_go(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "finance.Invoice@1")
    assert 'Amount string `json:"amount"`' in art.content
    assert 'TaxRate *string `json:"taxRate,omitempty"`' in art.content


def test_emit_go_fixed_width_integers_map_to_native_types(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain types {
  owner: "test-team"
  entity Widths @ 1 (additive) {
    @key id: uuid
    a: u8
    b: u16
    c: u32
    d: u64
    e: u128
    f: i8
    g: i16
    h: i32
    i: i64
    j: i128
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_go(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "types.Widths@1")
    assert 'A uint8 `json:"a"`' in art.content
    assert 'B uint16 `json:"b"`' in art.content
    assert 'C uint32 `json:"c"`' in art.content
    assert 'D uint64 `json:"d"`' in art.content
    assert 'E [16]byte `json:"e"`' in art.content
    assert 'F int8 `json:"f"`' in art.content
    assert 'G int16 `json:"g"`' in art.content
    assert 'H int32 `json:"h"`' in art.content
    assert 'I int64 `json:"i"`' in art.content
    assert 'J [16]byte `json:"j"`' in art.content
    assert len(art.warnings) == 2
    assert any("TypesWidthsV1.e" in warning for warning in art.warnings)
    assert any("TypesWidthsV1.j" in warning for warning in art.warnings)


def test_emit_go_temporal_types_inject_time_import(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain events {
  owner: "test-team"
  entity Event @ 1 (additive) {
    @key eventId: uuid
    occurredAt: timestamp
    scheduledDate: date
    windowStart: time
    ttl: duration
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_go(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "events.Event@1")
    assert "import (" in art.content
    assert '"time"' in art.content
    assert 'OccurredAt time.Time `json:"occurredAt"`' in art.content
    assert 'ScheduledDate time.Time `json:"scheduledDate"`' in art.content
    assert 'WindowStart time.Time `json:"windowStart"`' in art.content
    assert 'Ttl time.Duration `json:"ttl"`' in art.content


def test_emit_go_projection_uses_source_field_types(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  entity Customer @ 2 (additive) {
    @key customerId: uuid
    name: int
    email: string
  }

  projection CustomerView @ 2
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    name <- c.name
  }
}
""",
        encoding="utf-8",
    )
    from modelable.compiler.workspace import load_workspace

    workspace = load_workspace(tmp_path)
    artifacts = emit_go(workspace, tmp_path / "out")
    proj_art = next(a for a in artifacts if a.ref == "customer.CustomerView@2")
    # name comes from Customer@1 (string), not Customer@2 (int64)
    assert 'Name string `json:"name"`' in proj_art.content
