from __future__ import annotations

import os
import shutil
import subprocess

import yaml
from click.testing import CliRunner

from modelable.cli import cli
from modelable.compiler.workspace import load_workspace
from modelable.emitters.odcs import emit_odcs


def test_emit_odcs_model_and_projection(tmp_path):
    (tmp_path / "customer.mdl").write_text(
        """
domain customer {
  owner: "customer-team"
  contact: "customer-team@example.com"
  description: "Manage customers and accounts"

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    @pii
    @classification("confidential")
    @owner("identity-team")
    email: string
    status: enum(active, blocked)
    joinedAt?: timestamp
  }

  projection CustomerSummary @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    email <- c.email
    status <- c.status
    displayName = c.email
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_odcs(workspace, tmp_path / "out")

    model_art = next(art for art in artifacts if art.ref == "customer.Customer@1")
    assert model_art.target == "odcs"
    assert model_art.artifact_id == "customer.Customer.v1"
    assert model_art.path == tmp_path / "out" / "customer.Customer.v1.odcs.yaml"

    model_doc = yaml.safe_load(model_art.content.replace("# @generated by Modelable\n", ""))
    assert model_doc["apiVersion"] == "v3.1.0"
    assert model_doc["kind"] == "DataContract"
    assert model_doc["id"] == "modelable://customer/Customer/v1"
    assert model_doc["name"] == "customer.Customer.v1"
    assert model_doc["version"] == "1"
    assert model_doc["domain"] == "customer"
    assert model_doc["status"] == "active"
    assert model_doc["description"]["purpose"] == "Manage customers and accounts"
    assert _custom_properties(model_doc) == {
        "modelableRef": "customer.Customer@1",
        "modelableKind": "entity",
        "modelableChangeKind": "additive",
        "modelableOwner": "customer-team",
        "modelableContact": "customer-team@example.com",
    }

    schema = model_doc["schema"][0]
    assert schema["name"] == "Customer"
    assert schema["logicalType"] == "object"
    assert schema["physicalName"] == "Customer"

    customer_id = next(prop for prop in schema["properties"] if prop["name"] == "customerId")
    assert customer_id == {
        "name": "customerId",
        "logicalType": "string",
        "logicalTypeOptions": {"format": "uuid"},
        "required": True,
        "primaryKey": True,
        "customProperties": [{"property": "modelableType", "value": "uuid"}],
    }

    email = next(prop for prop in schema["properties"] if prop["name"] == "email")
    assert email == {
        "name": "email",
        "logicalType": "string",
        "required": True,
        "classification": "confidential",
        "customProperties": [
            {"property": "modelableType", "value": "string"},
            {"property": "modelablePii", "value": True},
            {"property": "modelableOwner", "value": "identity-team"},
        ],
    }

    status = next(prop for prop in schema["properties"] if prop["name"] == "status")
    assert status == {
        "name": "status",
        "logicalType": "string",
        "required": True,
        "customProperties": [
            {"property": "modelableType", "value": "enum(active,blocked)"},
            {"property": "modelableEnum", "value": ["active", "blocked"]},
        ],
    }

    joined_at = next(prop for prop in schema["properties"] if prop["name"] == "joinedAt")
    assert joined_at["logicalType"] == "timestamp"
    assert joined_at["required"] is False

    projection_art = next(art for art in artifacts if art.ref == "customer.CustomerSummary@1")
    projection_doc = yaml.safe_load(projection_art.content.replace("# @generated by Modelable\n", ""))
    assert _custom_properties(projection_doc) == {
        "modelableRef": "customer.CustomerSummary@1",
        "modelableKind": "projection",
        "modelableOwner": "customer-team",
        "modelableContact": "customer-team@example.com",
        "modelableSource": "customer.Customer@1",
    }

    projection_fields = projection_doc["schema"][0]["properties"]
    projection_email = next(prop for prop in projection_fields if prop["name"] == "email")
    assert projection_email["logicalType"] == "string"
    assert projection_email["classification"] == "confidential"
    assert _custom_properties(projection_email)["modelablePii"] is True
    assert _custom_properties(projection_email)["modelableLineage"] == ["customer.Customer@1.email"]

    display_name = next(prop for prop in projection_fields if prop["name"] == "displayName")
    assert display_name["logicalType"] == "string"
    assert _custom_properties(display_name)["modelableMapping"] == "computed"
    assert _custom_properties(display_name)["modelableExpression"] == "c.email"


def test_compile_odcs_writes_yaml_artifact(tmp_path):
    mdl = tmp_path / "customer.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "customer-team"

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    email?: string
  }
}
""",
        encoding="utf-8",
    )

    out = tmp_path / "dist"
    result = CliRunner().invoke(cli, ["compile", str(mdl), "--target", "odcs", "--out", str(out)])

    assert result.exit_code == 0, result.output
    artifact = out / "customer.Customer.v1.odcs.yaml"
    assert artifact.exists()
    doc = yaml.safe_load(artifact.read_text(encoding="utf-8").replace("# @generated by Modelable\n", ""))
    assert doc["apiVersion"] == "v3.1.0"
    assert doc["name"] == "customer.Customer.v1"


def test_compile_odcs_output_passes_datacontract_lint_when_available(tmp_path):
    datacontract = shutil.which("datacontract")
    if datacontract is None:
        if os.getenv("MODELABLE_DATACONTRACT_CLI") == "1":
            raise AssertionError("MODELABLE_DATACONTRACT_CLI=1 requires datacontract on PATH")
        return

    mdl = tmp_path / "customer.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "customer-team"

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    @pii
    @classification("confidential")
    email?: string
  }
}
""",
        encoding="utf-8",
    )

    out = tmp_path / "dist"
    result = CliRunner().invoke(cli, ["compile", str(mdl), "--target", "odcs", "--out", str(out)])

    assert result.exit_code == 0, result.output
    lint = subprocess.run(
        [datacontract, "lint", str(out / "customer.Customer.v1.odcs.yaml")],
        check=False,
        capture_output=True,
        text=True,
        encoding="utf-8",
        env={**os.environ, "PYTHONIOENCODING": "utf-8"},
    )

    assert lint.returncode == 0, lint.stdout + lint.stderr


def _custom_properties(node: dict) -> dict:
    return {entry["property"]: entry["value"] for entry in node["customProperties"]}
