import hashlib

from click.testing import CliRunner

from modelable.cli import cli
from modelable.compiler.workspace import load_workspace
from modelable.emitters.rust import emit_rust


def test_emit_rust_model_and_projection(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    tags: array<string>
    nickname?: string
    attributes?: map<string, int>
    address?: object {
      line1: string
      line2?: string
    }
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName <- c.displayName
    tags <- c.tags
    nickname <- c.nickname
    attributes <- c.attributes
    address <- c.address
  }
}
""",
        encoding="utf-8",
    )

    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    refs = {artifact.ref for artifact in artifacts}
    assert "customer.Customer@1" in refs
    assert "customer.CustomerView@1" in refs

    model_art = next(artifact for artifact in artifacts if artifact.ref == "customer.Customer@1")
    assert model_art.content_hash == hashlib.sha256(model_art.content.encode("utf-8")).hexdigest()
    assert model_art.path.as_posix().endswith("customer/customer_customer_v1.rs")
    assert "// @generated by Modelable" in model_art.content
    assert "use std::collections::HashMap;" in model_art.content
    assert "pub struct CustomerCustomerV1" in model_art.content
    assert "pub customer_id: uuid::Uuid," in model_art.content
    assert "pub display_name: String," in model_art.content
    assert "pub tags: Vec<String>," in model_art.content
    assert "pub nickname: Option<String>," in model_art.content
    assert "pub attributes: Option<HashMap<String, i64>>," in model_art.content
    assert "pub address: Option<CustomerCustomerV1Address>," in model_art.content
    assert "pub struct CustomerCustomerV1Address" in model_art.content
    assert "pub line1: String," in model_art.content
    assert "pub line2: Option<String>," in model_art.content

    proj_art = next(artifact for artifact in artifacts if artifact.ref == "customer.CustomerView@1")
    assert proj_art.content_hash == hashlib.sha256(proj_art.content.encode("utf-8")).hexdigest()
    assert proj_art.path.as_posix().endswith("customer/customer_customer_view_v1.rs")
    assert "pub struct CustomerCustomerViewV1" in proj_art.content
    assert "pub customer_id: uuid::Uuid," in proj_art.content
    assert "pub display_name: String," in proj_art.content
    assert "pub tags: Vec<String>," in proj_art.content
    assert "pub nickname: Option<String>," in proj_art.content
    assert "pub attributes: Option<HashMap<String, i64>>," in proj_art.content
    assert "pub address: Option<CustomerCustomerViewV1Address>," in proj_art.content
    assert "pub struct CustomerCustomerViewV1Address" in proj_art.content


def test_cli_compile_rust_writes_files(tmp_path):
    mdl = tmp_path / "customer.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    nickname?: string
  }
}
""",
        encoding="utf-8",
    )

    out = tmp_path / "dist" / "rust"
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path):
        result = runner.invoke(
            cli,
            ["compile", str(mdl), "--target", "rust", "--out", str(out)],
        )

    assert result.exit_code == 0, result.output
    assert (out / "customer" / "customer_customer_v1.rs").exists()
    assert any(len(part) == 64 and all(ch in "0123456789abcdef" for ch in part.lower()) for part in result.output.split())
    text = (out / "customer" / "customer_customer_v1.rs").read_text(encoding="utf-8")
    assert "pub struct CustomerCustomerV1" in text
    assert "pub customer_id: uuid::Uuid," in text
    assert "pub nickname: Option<String>," in text


def test_emit_rust_decimal_maps_to_string(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain finance {
  owner: "test-team"
  entity Invoice @ 1 (additive) {
    @key invoiceId: uuid
    amount: decimal(12, 2)
    taxRate?: decimal(5, 4)
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "finance.Invoice@1")
    assert "pub amount: String," in art.content
    assert "pub tax_rate: Option<String>," in art.content


def test_emit_rust_temporal_types_map_to_string(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain events {
  owner: "test-team"
  entity Event @ 1 (additive) {
    @key eventId: uuid
    occurredAt: timestamp
    scheduledDate: date
    windowStart: time
    ttl: duration
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "events.Event@1")
    assert "pub occurred_at: String," in art.content
    assert "pub scheduled_date: String," in art.content
    assert "pub window_start: String," in art.content
    assert "pub ttl: String," in art.content


def test_emit_rust_warns_on_computed_projection_field(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName = c.name + "!"
  }
}
""",
        encoding="utf-8",
    )
    from modelable.compiler.workspace import load_workspace
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj_art = next(a for a in artifacts if a.ref == "customer.CustomerView@1")
    assert proj_art.warnings
    assert any("EMIT002" in w for w in proj_art.warnings)


def test_emit_rust_projection_uses_source_field_types(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  entity Customer @ 2 (additive) {
    @key customerId: uuid
    name: int
    email: string
  }

  projection CustomerView @ 2
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    name <- c.name
  }
}
""",
        encoding="utf-8",
    )
    from modelable.compiler.workspace import load_workspace
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj_art = next(a for a in artifacts if a.ref == "customer.CustomerView@2")
    # name comes from Customer@1 (String), not Customer@2 (i64)
    assert "pub name: String," in proj_art.content


def test_emit_rust_struct_has_serde_derives(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain events {
  owner: "test-team"
  entity Event @ 1 (additive) {
    @key eventId: uuid
    name: string
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "events.Event@1")
    assert "serde::Serialize" in art.content
    assert "serde::Deserialize" in art.content


def test_emit_rust_nested_struct_has_serde_derives(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain events {
  owner: "test-team"
  entity Event @ 1 (additive) {
    @key eventId: uuid
    metadata: object {
      source: string
      priority: int
    }
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "events.Event@1")
    # Both the top-level struct and the nested object struct get serde derives
    assert art.content.count("serde::Serialize") == 2
    assert art.content.count("serde::Deserialize") == 2


def test_emit_rust_wire_u64_string_emits_serde_with(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain tracing {
  owner: "test-team"
  entity Span @ 1 (additive) {
    @key spanId: string
    @wire(json: "string", rust.type: "u64")
    startTimeUnixNano: int
    name: string
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "tracing.Span@1")
    # u64 field with json:string wire hint gets serde_with attribute
    assert "pub start_time_unix_nano: u64," in art.content
    assert 'serde_with::rust::display_fromstr' in art.content
    # plain string field does NOT get a serde_with attribute
    assert art.content.count('serde_with::rust::display_fromstr') == 1
    # file header documents the serde_with dependency
    assert "requires: serde_with" in art.content


def test_emit_rust_sqlx_fromrow_on_postgres_bound_projection(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain alerts {
  owner: "test-team"
  entity AlertRule @ 1 (additive) {
    @key ruleId: uuid
    name: string
    condition: string
  }

  projection AlertRuleRow @ 1
    from alerts.AlertRule @ 1 as a
  {
    ruleId <- a.ruleId
    name <- a.name
    condition <- a.condition
  }
}
""",
        encoding="utf-8",
    )
    (tmp_path / "bindings.mdl").write_text(
        """
binding alerts-pg {
  adapter: postgres
}

binding alert-rule-row-table {
  model: alerts.AlertRule @ 1
  adapter: alerts-pg
  table: "alert_rules"
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "alerts.AlertRuleRow@1")
    assert "sqlx::FromRow" in proj.content
    assert '#[cfg(feature = "storage")]' in proj.content
    assert "requires: sqlx" in proj.content
    # model struct is NOT storage-gated
    model = next(a for a in artifacts if a.ref == "alerts.AlertRule@1")
    assert "sqlx::FromRow" not in model.content
    assert '#[cfg(feature = "storage")]' not in model.content


def test_emit_rust_sqlx_fromrow_indirect_connector_binding(tmp_path):
    """Model binding via connector-binding name → adapter type resolved correctly."""
    (tmp_path / "all.mdl").write_text(
        """
domain orders {
  owner: "test-team"
  entity Order @ 1 (additive) {
    @key orderId: uuid
    total: int
  }

  projection OrderRow @ 1
    from orders.Order @ 1 as o
  {
    orderId <- o.orderId
    total <- o.total
  }
}

binding my-pg-conn {
  adapter: postgres
}

binding order-row-binding {
  model: orders.Order @ 1
  adapter: my-pg-conn
  table: "orders"
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "orders.OrderRow@1")
    assert "sqlx::FromRow" in proj.content
    assert '#[cfg(feature = "storage")]' in proj.content


def test_emit_rust_no_sqlx_without_binding(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain logs {
  owner: "test-team"
  entity Log @ 1 (additive) {
    @key logId: uuid
    message: string
  }

  projection LogView @ 1
    from logs.Log @ 1 as l
  {
    logId <- l.logId
    message <- l.message
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "logs.LogView@1")
    assert "sqlx::FromRow" not in proj.content
    assert '#[cfg(feature = "storage")]' not in proj.content


def test_emit_rust_clickhouse_row_on_clickhouse_bound_projection(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain telemetry {
  owner: "test-team"
  entity Span @ 1 (additive) {
    @key spanId: uuid
    tenantId: uuid
    name: string
  }

  projection SpanRow @ 1
    from telemetry.Span @ 1 as s
  {
    spanId <- s.spanId
    @wire(clickhouse: "uuid")
    tenantId <- s.tenantId
    name <- s.name
  }
}
""",
        encoding="utf-8",
    )
    (tmp_path / "bindings.mdl").write_text(
        """
binding ch-conn {
  adapter: clickhouse
}

binding span-row-binding {
  model: telemetry.Span @ 1
  adapter: ch-conn
  table: "spans"
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "telemetry.SpanRow@1")
    assert "clickhouse::Row" in proj.content
    assert '#[cfg(feature = "storage")]' in proj.content
    assert "requires: clickhouse" in proj.content
    assert '#[serde(with = "clickhouse::serde::uuid")]' in proj.content
    # model struct is NOT storage-gated
    model = next(a for a in artifacts if a.ref == "telemetry.Span@1")
    assert "clickhouse::Row" not in model.content
    assert '#[cfg(feature = "storage")]' not in model.content


def test_emit_rust_clickhouse_row_indirect_connector_binding(tmp_path):
    """Model binding via connector-binding name → adapter type resolved correctly for clickhouse."""
    (tmp_path / "all.mdl").write_text(
        """
domain events {
  owner: "test-team"
  entity LogEvent @ 1 (additive) {
    @key eventId: uuid
    message: string
  }

  projection LogEventRow @ 1
    from events.LogEvent @ 1 as e
  {
    eventId <- e.eventId
    message <- e.message
  }
}

binding my-ch-conn {
  adapter: clickhouse
}

binding log-event-binding {
  model: events.LogEvent @ 1
  adapter: my-ch-conn
  table: "log_events"
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "events.LogEventRow@1")
    assert "clickhouse::Row" in proj.content
    assert '#[cfg(feature = "storage")]' in proj.content


def test_emit_rust_no_clickhouse_without_binding(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain metrics {
  owner: "test-team"
  entity Metric @ 1 (additive) {
    @key metricId: uuid
    value: float
  }

  projection MetricView @ 1
    from metrics.Metric @ 1 as m
  {
    metricId <- m.metricId
    value <- m.value
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "metrics.MetricView@1")
    assert "clickhouse::Row" not in proj.content
    assert '#[cfg(feature = "storage")]' not in proj.content


def test_emit_rust_from_impl_basic(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    score: int
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName <- c.displayName
    score <- c.score
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "customer.CustomerView@1")
    assert "impl From<CustomerCustomerV1> for CustomerCustomerViewV1" in proj.content
    assert "fn from(src: CustomerCustomerV1) -> Self" in proj.content
    assert "customer_id: src.customer_id.into()," in proj.content
    assert "display_name: src.display_name.into()," in proj.content
    assert "use super::customer_customer_v1::CustomerCustomerV1;" in proj.content
    # Model struct itself should NOT have a From impl (no projection source)
    model = next(a for a in artifacts if a.ref == "customer.Customer@1")
    assert "impl From<" not in model.content


def test_emit_rust_from_impl_storage_gated(tmp_path):
    (tmp_path / "all.mdl").write_text(
        """
domain orders {
  owner: "test-team"
  entity Order @ 1 (additive) {
    @key orderId: uuid
    total: int
  }

  projection OrderRow @ 1
    from orders.Order @ 1 as o
  {
    orderId <- o.orderId
    total <- o.total
  }
}

binding my-pg-conn {
  adapter: postgres
}

binding order-binding {
  model: orders.Order @ 1
  adapter: my-pg-conn
  table: "orders"
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "orders.OrderRow@1")
    # From impl is present and storage-gated
    assert "impl From<OrdersOrderV1> for OrdersOrderRowV1" in proj.content
    assert proj.content.count('#[cfg(feature = "storage")]') >= 2  # struct + From impl


def test_emit_rust_from_impl_skipped_with_joins(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain sales {
  owner: "test-team"
  entity Order @ 1 (additive) {
    @key orderId: uuid
    customerId: uuid
  }

  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  projection OrderWithCustomer @ 1
    from sales.Order @ 1 as o
    join sales.Customer @ 1 as c on o.customerId == c.customerId
  {
    orderId <- o.orderId
    customerName <- c.name
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "sales.OrderWithCustomer@1")
    # No From impl generated for projections with joins
    assert "impl From<" not in proj.content


def test_emit_rust_from_impl_computed_field_defaults(tmp_path):
    (tmp_path / "model.mdl").write_text(
        """
domain customer {
  owner: "test-team"
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName = c.name + "!"
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj = next(a for a in artifacts if a.ref == "customer.CustomerView@1")
    assert "impl From<CustomerCustomerV1> for CustomerCustomerViewV1" in proj.content
    assert "display_name: Default::default()," in proj.content
    assert "// computed" in proj.content


def test_emit_rust_rust_type_without_json_string_no_serde_with(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain tracing {
  owner: "test-team"
  entity Span @ 1 (additive) {
    @key spanId: string
    @wire(rust.type: "u64")
    startTimeUnixNano: int
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    art = next(a for a in artifacts if a.ref == "tracing.Span@1")
    # rust.type alone (no json:string) does NOT need serde_with
    assert "pub start_time_unix_nano: u64," in art.content
    assert "serde_with" not in art.content


def test_emit_rust_projection_inherits_entity_wire_type(tmp_path):
    """rust.type on an entity field propagates to projection fields that map it."""
    (tmp_path / "model.mdl").write_text(
        """
domain tracing {
  owner: "test-team"
  entity Span @ 1 (additive) {
    @key spanId: string
    @wire(rust.type: "u64")
    startTimeUnixNano: int
  }

  projection SpanRow @ 1
    from tracing.Span @ 1 as s
  {
    spanId <- s.spanId
    startTimeUnixNano <- s.startTimeUnixNano
  }
}
""",
        encoding="utf-8",
    )
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    row_art = next(a for a in artifacts if a.ref == "tracing.SpanRow@1")
    # wire hint from the entity field must be inherited by the projection field
    assert "pub start_time_unix_nano: u64," in row_art.content
