import hashlib

from click.testing import CliRunner

from modelable.cli import cli
from modelable.compiler.workspace import load_workspace
from modelable.emitters.rust import emit_rust


def test_emit_rust_model_and_projection(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    tags: array<string>
    nickname?: string
    attributes?: map<string, int>
    address?: object {
      line1: string
      line2?: string
    }
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName <- c.displayName
    tags <- c.tags
    nickname <- c.nickname
    attributes <- c.attributes
    address <- c.address
  }
}
""",
        encoding="utf-8",
    )

    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    refs = {artifact.ref for artifact in artifacts}
    assert "customer.Customer@1" in refs
    assert "customer.CustomerView@1" in refs

    model_art = next(artifact for artifact in artifacts if artifact.ref == "customer.Customer@1")
    assert model_art.content_hash == hashlib.sha256(model_art.content.encode("utf-8")).hexdigest()
    assert model_art.path.as_posix().endswith("customer/customer_customer_v1.rs")
    assert "// @generated by Modelable" in model_art.content
    assert "use std::collections::HashMap;" in model_art.content
    assert "pub struct CustomerCustomerV1" in model_art.content
    assert "pub customer_id: String," in model_art.content
    assert "pub display_name: String," in model_art.content
    assert "pub tags: Vec<String>," in model_art.content
    assert "pub nickname: Option<String>," in model_art.content
    assert "pub attributes: Option<HashMap<String, i64>>," in model_art.content
    assert "pub address: Option<CustomerCustomerV1Address>," in model_art.content
    assert "pub struct CustomerCustomerV1Address" in model_art.content
    assert "pub line1: String," in model_art.content
    assert "pub line2: Option<String>," in model_art.content

    proj_art = next(artifact for artifact in artifacts if artifact.ref == "customer.CustomerView@1")
    assert proj_art.content_hash == hashlib.sha256(proj_art.content.encode("utf-8")).hexdigest()
    assert proj_art.path.as_posix().endswith("customer/customer_customer_view_v1.rs")
    assert "pub struct CustomerCustomerViewV1" in proj_art.content
    assert "pub customer_id: String," in proj_art.content
    assert "pub display_name: String," in proj_art.content
    assert "pub tags: Vec<String>," in proj_art.content
    assert "pub nickname: Option<String>," in proj_art.content
    assert "pub attributes: Option<HashMap<String, i64>>," in proj_art.content
    assert "pub address: Option<CustomerCustomerViewV1Address>," in proj_art.content
    assert "pub struct CustomerCustomerViewV1Address" in proj_art.content


def test_cli_compile_rust_writes_files(tmp_path):
    mdl = tmp_path / "customer.mdl"
    mdl.write_text(
        """
domain customer {
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    displayName: string
    nickname?: string
  }
}
""",
        encoding="utf-8",
    )

    out = tmp_path / "dist" / "rust"
    runner = CliRunner()
    with runner.isolated_filesystem(temp_dir=tmp_path):
        result = runner.invoke(
            cli,
            ["compile", str(mdl), "--target", "rust", "--out", str(out)],
        )

    assert result.exit_code == 0, result.output
    assert (out / "customer" / "customer_customer_v1.rs").exists()
    assert any(len(part) == 64 and all(ch in "0123456789abcdef" for ch in part.lower()) for part in result.output.split())
    text = (out / "customer" / "customer_customer_v1.rs").read_text(encoding="utf-8")
    assert "pub struct CustomerCustomerV1" in text
    assert "pub customer_id: String," in text
    assert "pub nickname: Option<String>," in text


def test_emit_rust_warns_on_computed_projection_field(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  projection CustomerView @ 1
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    displayName = c.name + "!"
  }
}
""",
        encoding="utf-8",
    )
    from modelable.compiler.workspace import load_workspace
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj_art = next(a for a in artifacts if a.ref == "customer.CustomerView@1")
    assert proj_art.warnings
    assert any("EMIT002" in w for w in proj_art.warnings)


def test_emit_rust_projection_uses_source_field_types(tmp_path):
    mdl = tmp_path / "test.mdl"
    mdl.write_text(
        """
domain customer {
  entity Customer @ 1 (additive) {
    @key customerId: uuid
    name: string
  }

  entity Customer @ 2 (additive) {
    @key customerId: uuid
    name: int
    email: string
  }

  projection CustomerView @ 2
    from customer.Customer @ 1 as c
  {
    customerId <- c.customerId
    name <- c.name
  }
}
""",
        encoding="utf-8",
    )
    from modelable.compiler.workspace import load_workspace
    workspace = load_workspace(tmp_path)
    artifacts = emit_rust(workspace, tmp_path / "out")
    proj_art = next(a for a in artifacts if a.ref == "customer.CustomerView@2")
    # name comes from Customer@1 (String), not Customer@2 (i64)
    assert "pub name: String," in proj_art.content
