-- @generated by Modelable
-- catalog.ProductReply v1
CREATE TABLE IF NOT EXISTS product_reply
(
    product_id UUID,
    name String
) ENGINE = MergeTree()
ORDER BY tuple(); -- TODO: set ORDER BY for production use
