-- @generated by Modelable
-- customer.CustomerDb v1
CREATE TABLE IF NOT EXISTS customer_db
(
    customer_id UUID,
    display_name String,
    email String,
    internal_risk_notes Nullable(String),
    status LowCardinality(String),
    tags Array(String),
    metadata Map(String, Int64),
    address Nullable(String),
    favorite_product Nullable(String),
    created_at DateTime64(9),
    updated_at Nullable(DateTime64(9)),
    INDEX idx_by_email (email) TYPE bloom_filter GRANULARITY 1,
    INDEX idx_by_status (status) TYPE bloom_filter GRANULARITY 1
) ENGINE = MergeTree()
ORDER BY tuple(); -- TODO: set ORDER BY for production use
