-- @generated by Modelable
-- customer.CustomerRequest v1
CREATE TABLE IF NOT EXISTS customer_request
(
    customer_id UUID,
    display_name String,
    email String,
    status LowCardinality(String),
    tags Array(String),
    metadata Map(String, Int64),
    address Nullable(String),
    favorite_product Nullable(String),
    INDEX idx_by_email (email) TYPE bloom_filter GRANULARITY 1,
    INDEX idx_by_status (status) TYPE bloom_filter GRANULARITY 1
) ENGINE = MergeTree()
ORDER BY tuple(); -- TODO: set ORDER BY for production use
