// @generated by Modelable
// requires: uuid (https://docs.rs/uuid)

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct CatalogProductReplyV1 {
    #[serde(rename = "productId")]
    pub product_id: uuid::Uuid,
    pub name: String,
}

impl CatalogProductReplyV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0xf4, 0x30, 0xbc, 0x21, 0x51, 0x88, 0xe6, 0x77,
        0xa3, 0x29, 0x6b, 0x59, 0xd3, 0x27, 0xfc, 0x33,
        0xf9, 0x3a, 0x18, 0x1e, 0xc4, 0x7c, 0xfd, 0xe9,
        0xf5, 0x53, 0x9a, 0xe9, 0xe0, 0xb7, 0x1b, 0xab,
    ];
}

use super::catalog_product_v1::CatalogProductV1;
#[allow(clippy::useless_conversion)]
impl From<CatalogProductV1> for CatalogProductReplyV1 {
    fn from(src: CatalogProductV1) -> Self {
        Self {
            product_id: src.product_id.into(),
            name: src.name.into(),
        }
    }
}
