#:schema ../../../../cli/src/modelable/schemas/overlays/sql-postgres-v1.schema.json

target = "sql-postgres"
version = 1

[models."warehouse.StockItem@*"]
table = "warehouse_stock"

[fields."warehouse.StockItem@1#quantityOnHand"]
column = "qty_on_hand"
