{
  "type": "record",
  "name": "CustomerV1",
  "namespace": "customer",
  "fields": [
    {
      "name": "customerId",
      "type": {
        "type": "string",
        "logicalType": "uuid"
      }
    },
    {
      "name": "displayName",
      "type": "string"
    },
    {
      "name": "email",
      "type": "string"
    },
    {
      "name": "internalRiskNotes",
      "type": [
        "null",
        "string"
      ],
      "default": null
    },
    {
      "name": "status",
      "type": {
        "type": "enum",
        "name": "CustomerstatusEnum",
        "symbols": [
          "active",
          "suspended",
          "deleted"
        ]
      }
    },
    {
      "name": "tags",
      "type": {
        "type": "array",
        "items": "string"
      }
    },
    {
      "name": "metadata",
      "type": {
        "type": "map",
        "values": "int"
      }
    },
    {
      "name": "address",
      "type": [
        "null",
        {
          "type": "record",
          "name": "Customeraddress",
          "fields": [
            {
              "name": "line1",
              "type": "string"
            },
            {
              "name": "line2",
              "type": [
                "null",
                "string"
              ]
            }
          ]
        }
      ],
      "default": null
    },
    {
      "name": "favoriteProduct",
      "type": [
        "null",
        {
          "type": "string",
          "logicalType": "uuid"
        }
      ],
      "default": null
    },
    {
      "name": "createdAt",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      }
    },
    {
      "name": "updatedAt",
      "type": [
        "null",
        {
          "type": "long",
          "logicalType": "timestamp-millis"
        }
      ],
      "default": null
    }
  ],
  "x-modelable": {
    "ref": "customer.Customer@1",
    "kind": "model",
    "version": 1
  }
}
