// @generated by Modelable
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PlatformWidgetV1 {
    pub widget_id: uuid::Uuid,
    pub legacy_id: uuid::Uuid,
    pub name: String,
    pub quantity: i64,
    pub weight: f64,
    pub active: bool,
    pub created_at: String,
    pub born_on: String,
    pub daily_at: String,
    pub ttl: String,
    pub blob: Vec<u8>,
    pub checksum: [u8; 32],
    pub price: String,
    pub small_count: u8,
    pub medium_count: u16,
    pub big_count: u32,
    pub huge_count: u64,
    pub massive_count: u128,
    pub small_delta: i8,
    pub medium_delta: i16,
    pub big_delta: i32,
    pub huge_delta: i64,
    pub massive_delta: i128,
    pub status: PlatformWidgetV1Status,
    pub tags: Vec<String>,
    pub attributes: HashMap<String, i64>,
}

impl PlatformWidgetV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0xa2, 0x8c, 0xd9, 0x0f, 0x00, 0x00, 0xd0, 0x7b,
        0x90, 0xab, 0x69, 0xe1, 0xf0, 0x8d, 0xf4, 0x25,
        0x6f, 0x6f, 0x56, 0x6a, 0x75, 0x4f, 0xb0, 0xa0,
        0xbb, 0x1d, 0x96, 0x32, 0xb7, 0xd7, 0x5b, 0xe7,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum PlatformWidgetV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "discontinued")]
    Discontinued,
}
