// @generated by Modelable
// requires: chrono (https://docs.rs/chrono)
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;


mod modelable_duration {
    use serde::{Deserialize, Deserializer, Serializer};

    pub fn serialize<S>(value: &chrono::Duration, serializer: S) -> Result<S::Ok, S::Error>
    where
        S: Serializer,
    {
        serializer.serialize_str(&value.to_string())
    }

    pub fn deserialize<'de, D>(deserializer: D) -> Result<chrono::Duration, D::Error>
    where
        D: Deserializer<'de>,
    {
        let value = String::deserialize(deserializer)?;
        parse(&value).map_err(serde::de::Error::custom)
    }

    pub mod option {
        use super::parse;
        use serde::{Deserialize, Deserializer, Serialize, Serializer};

        pub fn serialize<S>(value: &Option<chrono::Duration>, serializer: S) -> Result<S::Ok, S::Error>
        where
            S: Serializer,
        {
            value.as_ref().map(ToString::to_string).serialize(serializer)
        }

        pub fn deserialize<'de, D>(deserializer: D) -> Result<Option<chrono::Duration>, D::Error>
        where
            D: Deserializer<'de>,
        {
            Option::<String>::deserialize(deserializer)?
                .map(|value| parse(&value).map_err(serde::de::Error::custom))
                .transpose()
        }
    }

    fn parse(value: &str) -> Result<chrono::Duration, String> {
        let (negative, body) = value.strip_prefix('-').map_or((false, value), |rest| (true, rest));
        let body = body.strip_prefix('P').ok_or_else(|| "duration must start with P".to_string())?;
        let mut total_nanos: i128 = 0;
        let mut number = String::new();
        let mut in_time = false;
        for ch in body.chars() {
            if ch.is_ascii_digit() || ch == '.' {
                number.push(ch);
                continue;
            }
            if ch == 'T' && number.is_empty() && !in_time {
                in_time = true;
                continue;
            }
            if number.is_empty() || (!in_time && ch != 'D') || (in_time && !matches!(ch, 'H' | 'M' | 'S')) {
                return Err(format!("unsupported ISO-8601 duration component: {ch}"));
            }
            let unit_nanos: i128 = match ch { 'D' => 86_400_000_000_000, 'H' => 3_600_000_000_000, 'M' => 60_000_000_000, 'S' => 1_000_000_000, _ => unreachable!() };
            let component = if ch == 'S' && number.contains('.') {
                let (whole, fraction) = number.split_once('.').unwrap();
                let nanos = format!("{fraction:0<9}").chars().take(9).collect::<String>().parse::<i128>().map_err(|_| "invalid duration fraction".to_string())?;
                whole.parse::<i128>().map_err(|_| "invalid duration seconds".to_string())? * unit_nanos + nanos
            } else {
                number.parse::<i128>().map_err(|_| "invalid duration component".to_string())? * unit_nanos
            };
            total_nanos = total_nanos.checked_add(component).ok_or_else(|| "duration is out of range".to_string())?;
            number.clear();
        }
        if !number.is_empty() || total_nanos == 0 && body.is_empty() {
            return Err("duration has an incomplete component".to_string());
        }
        let total_nanos = if negative { -total_nanos } else { total_nanos };
        let total_nanos = i64::try_from(total_nanos).map_err(|_| "duration is out of range".to_string())?;
        Ok(chrono::Duration::nanoseconds(total_nanos))
    }
}
#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PlatformWidgetV1 {
    pub widget_id: uuid::Uuid,
    pub legacy_id: uuid::Uuid,
    pub name: String,
    pub quantity: i64,
    pub weight: f64,
    pub active: bool,
    pub created_at: chrono::DateTime<chrono::Utc>,
    pub born_on: chrono::NaiveDate,
    pub daily_at: chrono::NaiveTime,
    #[serde(with = "modelable_duration")]
    pub ttl: chrono::Duration,
    pub blob: Vec<u8>,
    pub checksum: [u8; 32],
    pub price: String,
    pub small_count: u8,
    pub medium_count: u16,
    pub big_count: u32,
    pub huge_count: u64,
    pub massive_count: u128,
    pub small_delta: i8,
    pub medium_delta: i16,
    pub big_delta: i32,
    pub huge_delta: i64,
    pub massive_delta: i128,
    pub status: PlatformWidgetV1Status,
    pub tags: Vec<String>,
    pub attributes: HashMap<String, i64>,
}

impl PlatformWidgetV1 {
    pub const SCHEMA_VERSION: u32 = 1;
    pub const SCHEMA_CONTENT_SIGNATURE: [u8; 32] = [
        0xa2, 0x8c, 0xd9, 0x0f, 0x00, 0x00, 0xd0, 0x7b,
        0x90, 0xab, 0x69, 0xe1, 0xf0, 0x8d, 0xf4, 0x25,
        0x6f, 0x6f, 0x56, 0x6a, 0x75, 0x4f, 0xb0, 0xa0,
        0xbb, 0x1d, 0x96, 0x32, 0xb7, 0xd7, 0x5b, 0xe7,
    ];
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum PlatformWidgetV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "discontinued")]
    Discontinued,
}
