// @generated by Modelable
// requires: uuid (https://docs.rs/uuid)
use std::collections::HashMap;

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub struct PlatformWidgetV1 {
    pub widget_id: uuid::Uuid,
    pub legacy_id: uuid::Uuid,
    pub name: String,
    pub quantity: i64,
    pub weight: f64,
    pub active: bool,
    pub created_at: String,
    pub born_on: String,
    pub daily_at: String,
    pub ttl: String,
    pub blob: Vec<u8>,
    pub checksum: [u8; 32],
    pub price: String,
    pub small_count: u8,
    pub medium_count: u16,
    pub big_count: u32,
    pub huge_count: u64,
    pub massive_count: u128,
    pub small_delta: i8,
    pub medium_delta: i16,
    pub big_delta: i32,
    pub huge_delta: i64,
    pub massive_delta: i128,
    pub status: PlatformWidgetV1Status,
    pub tags: Vec<String>,
    pub attributes: HashMap<String, i64>,
}

#[derive(Debug, Clone, PartialEq, serde::Serialize, serde::Deserialize)]
pub enum PlatformWidgetV1Status {
    #[serde(rename = "active")]
    Active,
    #[serde(rename = "inactive")]
    Inactive,
    #[serde(rename = "discontinued")]
    Discontinued,
}
