// Code generated by Modelable; DO NOT EDIT.
package customer

import (
    "time"
)

type CustomerCustomerEventV1 struct {
    CustomerId string `json:"customerId"`
    DisplayName string `json:"displayName"`
    Email string `json:"email"`
    Status string `json:"status"`
    Tags []string `json:"tags"`
    Metadata map[string]int64 `json:"metadata"`
    CreatedAt time.Time `json:"createdAt"`
    InternalRiskNotes *string `json:"internalRiskNotes,omitempty"`
    Address *CustomerCustomerEventV1Address `json:"address,omitempty"`
    FavoriteProduct *string `json:"favoriteProduct,omitempty"`
    UpdatedAt *time.Time `json:"updatedAt,omitempty"`
}

type CustomerCustomerEventV1Address struct {
    Line1 string `json:"line1"`
    Line2 *string `json:"line2,omitempty"`
}
