// Code generated by Modelable; DO NOT EDIT.
package customer

type CustomerCustomerRequestV1 struct {
    CustomerId string `json:"customerId"`
    DisplayName string `json:"displayName"`
    Email string `json:"email"`
    Status string `json:"status"`
    Tags []string `json:"tags"`
    Metadata map[string]int64 `json:"metadata"`
    Address *CustomerCustomerRequestV1Address `json:"address,omitempty"`
    FavoriteProduct *string `json:"favoriteProduct,omitempty"`
}

type CustomerCustomerRequestV1Address struct {
    Line1 string `json:"line1"`
    Line2 *string `json:"line2,omitempty"`
}
