"""Artifact format and language registry for Modellable code generation targets."""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal

ArtifactCategory = Literal[
    "api_spec", "typed_language", "serialization", "sql_ddl", "data_tool"
]

# All 16 Modellable field types, in canonical order.
MODELLABLE_TYPES = [
    "string", "boolean", "integer", "decimal", "float",
    "timestamp", "date", "time", "duration", "uuid", "binary",
    "enum", "array", "object", "map", "reference",
]


@dataclass
class ArtifactFormat:
    id: str
    name: str
    category: ArtifactCategory
    file_extension: str
    description: str
    # Maps each Modellable type to the idiomatic native type string.
    type_map: dict[str, str]
    # Optional per-type caveats shown alongside the type.
    notes: dict[str, str] = field(default_factory=dict)


# ---------------------------------------------------------------------------
# Registry — keyed by the format id used in YAML `artifacts[].format` fields.
# ---------------------------------------------------------------------------

ARTIFACT_FORMATS: dict[str, ArtifactFormat] = {

    # ── API Specification formats ──────────────────────────────────────────

    "openapi_3_1": ArtifactFormat(
        id="openapi_3_1",
        name="OpenAPI 3.1",
        category="api_spec",
        file_extension=".yaml",
        description="OpenAPI 3.1 REST specification (JSON Schema 2020-12 vocab; nullability via type arrays).",
        type_map={
            "string":    "string",
            "boolean":   "boolean",
            "integer":   "integer (format: int64)",
            "decimal":   "number",
            "float":     "number (format: float)",
            "timestamp": "string (format: date-time)",
            "date":      "string (format: date)",
            "time":      "string (format: time)",
            "duration":  "string (format: duration)",
            "uuid":      "string (format: uuid)",
            "binary":    "string (format: binary)",
            "enum":      "string (enum: [...])",
            "array":     "array (items: {...})",
            "object":    "object",
            "map":       "object (additionalProperties: {...})",
            "reference": "$ref: '#/components/schemas/Name'",
        },
    ),

    "openapi_3_0": ArtifactFormat(
        id="openapi_3_0",
        name="OpenAPI 3.0",
        category="api_spec",
        file_extension=".yaml",
        description="OpenAPI 3.0 specification (Swagger-derived; nullable via `nullable: true` property).",
        type_map={
            "string":    "string",
            "boolean":   "boolean",
            "integer":   "integer (format: int64)",
            "decimal":   "number",
            "float":     "number (format: float)",
            "timestamp": "string (format: date-time)",
            "date":      "string (format: date)",
            "time":      "string (format: time)",
            "duration":  "string",
            "uuid":      "string",
            "binary":    "string (format: binary)",
            "enum":      "string (enum: [...])",
            "array":     "array (items: {...})",
            "object":    "object",
            "map":       "object (additionalProperties: {...})",
            "reference": "$ref: '#/components/schemas/Name'",
        },
        notes={
            "duration": "No official format; use plain string with ISO 8601 convention.",
            "uuid":     "No official format in OAS 3.0; use plain string.",
        },
    ),

    "json_schema": ArtifactFormat(
        id="json_schema",
        name="JSON Schema",
        category="api_spec",
        file_extension=".json",
        description="JSON Schema (2020-12 draft) type definitions.",
        type_map={
            "string":    '{"type": "string"}',
            "boolean":   '{"type": "boolean"}',
            "integer":   '{"type": "integer", "format": "int64"}',
            "decimal":   '{"type": "number"}',
            "float":     '{"type": "number"}',
            "timestamp": '{"type": "string", "format": "date-time"}',
            "date":      '{"type": "string", "format": "date"}',
            "time":      '{"type": "string", "format": "time"}',
            "duration":  '{"type": "string", "format": "duration"}',
            "uuid":      '{"type": "string", "format": "uuid"}',
            "binary":    '{"type": "string", "contentEncoding": "base64"}',
            "enum":      '{"type": "string", "enum": [...]}',
            "array":     '{"type": "array", "items": {...}}',
            "object":    '{"type": "object"}',
            "map":       '{"type": "object", "additionalProperties": {...}}',
            "reference": '{"$ref": "#/$defs/Name"}',
        },
    ),

    "graphql": ArtifactFormat(
        id="graphql",
        name="GraphQL SDL",
        category="api_spec",
        file_extension=".graphql",
        description="GraphQL Schema Definition Language (SDL) types and scalars.",
        type_map={
            "string":    "String",
            "boolean":   "Boolean",
            "integer":   "Int (32-bit) / BigInt (custom scalar for 64-bit)",
            "decimal":   "Float (or custom scalar Decimal)",
            "float":     "Float",
            "timestamp": "String (or custom scalar DateTime)",
            "date":      "String (or custom scalar Date)",
            "time":      "String (or custom scalar Time)",
            "duration":  "String (or custom scalar Duration)",
            "uuid":      "ID / String",
            "binary":    "String (base64-encoded)",
            "enum":      "enum TypeName { VALUE_A VALUE_B }",
            "array":     "[T] (non-null: [T!]!)",
            "object":    "type TypeName { ... }",
            "map":       "JSON (custom scalar) or list of key-value types",
            "reference": "TypeName",
        },
        notes={
            "integer": "GraphQL Int is 32-bit signed. Use a custom BigInt scalar for int64.",
            "map":     "GraphQL has no native map type; use a JSON scalar or List(KeyValue).",
        },
    ),

    "asyncapi_3": ArtifactFormat(
        id="asyncapi_3",
        name="AsyncAPI 3",
        category="api_spec",
        file_extension=".yaml",
        description="AsyncAPI 3.0 event-driven specification (channels, messages, schemas).",
        type_map={
            "string":    "string",
            "boolean":   "boolean",
            "integer":   "integer (format: int64)",
            "decimal":   "number",
            "float":     "number (format: float)",
            "timestamp": "string (format: date-time)",
            "date":      "string (format: date)",
            "time":      "string (format: time)",
            "duration":  "string (format: duration)",
            "uuid":      "string (format: uuid)",
            "binary":    "string (contentEncoding: base64)",
            "enum":      "string (enum: [...])",
            "array":     "array (items: {...})",
            "object":    "object",
            "map":       "object (additionalProperties: {...})",
            "reference": "$ref: '#/components/schemas/Name'",
        },
    ),

    "grpc": ArtifactFormat(
        id="grpc",
        name="gRPC (Protobuf + service)",
        category="api_spec",
        file_extension=".proto",
        description="gRPC service + message definitions using proto3 syntax (same types as protobuf).",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "int64",
            "decimal":   "string (encode as decimal string; no native type)",
            "float":     "double",
            "timestamp": "google.protobuf.Timestamp",
            "date":      "google.type.Date",
            "time":      "google.type.TimeOfDay",
            "duration":  "google.protobuf.Duration",
            "uuid":      "string",
            "binary":    "bytes",
            "enum":      "enum EnumName { UNSPECIFIED = 0; VALUE_A = 1; }",
            "array":     "repeated T",
            "object":    "google.protobuf.Struct",
            "map":       "map<string, V>",
            "reference": "MessageName",
        },
        notes={
            "decimal": "Proto3 has no decimal type. Encode as string or use a custom message with int + scale.",
        },
    ),

    # ── Typed programming languages ────────────────────────────────────────

    "typescript": ArtifactFormat(
        id="typescript",
        name="TypeScript",
        category="typed_language",
        file_extension=".d.ts",
        description="TypeScript interface / type alias declarations (ESM-compatible).",
        type_map={
            "string":    "string",
            "boolean":   "boolean",
            "integer":   "number",
            "decimal":   "number (or Decimal from decimal.js for precision)",
            "float":     "number",
            "timestamp": "string | Date",
            "date":      "string",
            "time":      "string",
            "duration":  "string",
            "uuid":      "string",
            "binary":    "Uint8Array | Buffer",
            "enum":      "enum TypeName { A = 'A', B = 'B' } or 'A' | 'B'",
            "array":     "Array<T> / T[]",
            "object":    "Record<string, unknown>",
            "map":       "Map<string, V> | Record<string, V>",
            "reference": "ModelName",
        },
        notes={
            "integer": "TypeScript has a single `number` type; use `bigint` if values exceed 2^53.",
            "decimal": "JavaScript floats lose precision; use Decimal.js or similar for financial data.",
        },
    ),

    "javascript": ArtifactFormat(
        id="javascript",
        name="JavaScript (JSDoc)",
        category="typed_language",
        file_extension=".js",
        description="JavaScript with JSDoc type annotations (@typedef / @type comments).",
        type_map={
            "string":    "string",
            "boolean":   "boolean",
            "integer":   "number",
            "decimal":   "number",
            "float":     "number",
            "timestamp": "string | Date",
            "date":      "string",
            "time":      "string",
            "duration":  "string",
            "uuid":      "string",
            "binary":    "Uint8Array",
            "enum":      "@typedef {'A'|'B'} EnumName",
            "array":     "Array<T>",
            "object":    "Object.<string, *>",
            "map":       "Map | Object.<string, V>",
            "reference": "ModelName",
        },
    ),

    "python_pydantic": ArtifactFormat(
        id="python_pydantic",
        name="Python (Pydantic v2)",
        category="typed_language",
        file_extension=".py",
        description="Python Pydantic v2 BaseModel class definitions with full type hints.",
        type_map={
            "string":    "str",
            "boolean":   "bool",
            "integer":   "int",
            "decimal":   "Decimal (from decimal import Decimal)",
            "float":     "float",
            "timestamp": "datetime (from datetime import datetime)",
            "date":      "date (from datetime import date)",
            "time":      "time (from datetime import time)",
            "duration":  "timedelta (from datetime import timedelta)",
            "uuid":      "UUID (from uuid import UUID)",
            "binary":    "bytes",
            "enum":      "StrEnum / Enum (from enum import Enum)",
            "array":     "list[T]",
            "object":    "dict[str, Any]",
            "map":       "dict[K, V]",
            "reference": "ModelName (forward ref as 'ModelName')",
        },
    ),

    "python_dataclass": ArtifactFormat(
        id="python_dataclass",
        name="Python (dataclass)",
        category="typed_language",
        file_extension=".py",
        description="Python standard-library @dataclass definitions with type hints.",
        type_map={
            "string":    "str",
            "boolean":   "bool",
            "integer":   "int",
            "decimal":   "Decimal",
            "float":     "float",
            "timestamp": "datetime",
            "date":      "date",
            "time":      "time",
            "duration":  "timedelta",
            "uuid":      "UUID",
            "binary":    "bytes",
            "enum":      "Enum",
            "array":     "list[T]",
            "object":    "dict[str, Any]",
            "map":       "dict[K, V]",
            "reference": "ModelName",
        },
    ),

    "go": ArtifactFormat(
        id="go",
        name="Go",
        category="typed_language",
        file_extension=".go",
        description="Go struct definitions with `json:` struct tags.",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "int64",
            "decimal":   "float64 (or shopspring/decimal.Decimal)",
            "float":     "float64",
            "timestamp": "time.Time",
            "date":      "time.Time (date portion only)",
            "time":      "time.Time",
            "duration":  "time.Duration",
            "uuid":      "string (or google/uuid.UUID)",
            "binary":    "[]byte",
            "enum":      "string (with typed const block)",
            "array":     "[]T",
            "object":    "map[string]interface{}",
            "map":       "map[K]V",
            "reference": "*StructName",
        },
        notes={
            "decimal": "Go has no built-in decimal type; use shopspring/decimal for financial precision.",
        },
    ),

    "java": ArtifactFormat(
        id="java",
        name="Java",
        category="typed_language",
        file_extension=".java",
        description="Java POJO / record definitions with Jackson annotations.",
        type_map={
            "string":    "String",
            "boolean":   "Boolean / boolean",
            "integer":   "Long / long",
            "decimal":   "BigDecimal (java.math)",
            "float":     "Double / double",
            "timestamp": "Instant (java.time)",
            "date":      "LocalDate (java.time)",
            "time":      "LocalTime (java.time)",
            "duration":  "Duration (java.time)",
            "uuid":      "UUID (java.util)",
            "binary":    "byte[]",
            "enum":      "enum EnumName { A, B }",
            "array":     "List<T> (java.util)",
            "object":    "Map<String, Object>",
            "map":       "Map<K, V>",
            "reference": "ClassName",
        },
    ),

    "kotlin": ArtifactFormat(
        id="kotlin",
        name="Kotlin",
        category="typed_language",
        file_extension=".kt",
        description="Kotlin data class definitions, compatible with Jackson / kotlinx.serialization.",
        type_map={
            "string":    "String",
            "boolean":   "Boolean",
            "integer":   "Long",
            "decimal":   "BigDecimal (java.math)",
            "float":     "Double",
            "timestamp": "Instant (kotlinx.datetime or java.time)",
            "date":      "LocalDate",
            "time":      "LocalTime",
            "duration":  "Duration (kotlin.time)",
            "uuid":      "java.util.UUID",
            "binary":    "ByteArray",
            "enum":      "enum class EnumName { A, B }",
            "array":     "List<T>",
            "object":    "Map<String, Any>",
            "map":       "Map<K, V>",
            "reference": "ClassName",
        },
    ),

    "rust": ArtifactFormat(
        id="rust",
        name="Rust",
        category="typed_language",
        file_extension=".rs",
        description="Rust struct definitions with serde Serialize/Deserialize derives.",
        type_map={
            "string":    "String / &str",
            "boolean":   "bool",
            "integer":   "i64",
            "decimal":   "Decimal (rust_decimal crate)",
            "float":     "f64",
            "timestamp": "DateTime<Utc> (chrono)",
            "date":      "NaiveDate (chrono)",
            "time":      "NaiveTime (chrono)",
            "duration":  "Duration (chrono)",
            "uuid":      "Uuid (uuid crate)",
            "binary":    "Vec<u8> / Bytes (bytes crate)",
            "enum":      "#[derive(Serialize, Deserialize)] enum Name { A, B }",
            "array":     "Vec<T>",
            "object":    "HashMap<String, serde_json::Value>",
            "map":       "HashMap<K, V>",
            "reference": "StructName",
        },
    ),

    "csharp": ArtifactFormat(
        id="csharp",
        name="C#",
        category="typed_language",
        file_extension=".cs",
        description="C# record / class definitions with System.Text.Json or Newtonsoft.Json attributes.",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "long",
            "decimal":   "decimal",
            "float":     "double",
            "timestamp": "DateTimeOffset",
            "date":      "DateOnly (.NET 6+)",
            "time":      "TimeOnly (.NET 6+)",
            "duration":  "TimeSpan",
            "uuid":      "Guid",
            "binary":    "byte[]",
            "enum":      "enum EnumName { A, B }",
            "array":     "IReadOnlyList<T> / List<T>",
            "object":    "Dictionary<string, object>",
            "map":       "Dictionary<TKey, TValue>",
            "reference": "ClassName",
        },
    ),

    "swift": ArtifactFormat(
        id="swift",
        name="Swift",
        category="typed_language",
        file_extension=".swift",
        description="Swift Codable struct/enum definitions.",
        type_map={
            "string":    "String",
            "boolean":   "Bool",
            "integer":   "Int64",
            "decimal":   "Decimal",
            "float":     "Double",
            "timestamp": "Date",
            "date":      "Date (encode as ISO 8601 string)",
            "time":      "DateComponents / String",
            "duration":  "Duration (Swift 5.7+) / TimeInterval",
            "uuid":      "UUID",
            "binary":    "Data",
            "enum":      "enum Name: String, Codable { case a = \"a\" }",
            "array":     "[T]",
            "object":    "[String: Any]",
            "map":       "[Key: Value]",
            "reference": "StructName",
        },
    ),

    "scala": ArtifactFormat(
        id="scala",
        name="Scala",
        category="typed_language",
        file_extension=".scala",
        description="Scala case class definitions, compatible with Circe / Play JSON.",
        type_map={
            "string":    "String",
            "boolean":   "Boolean",
            "integer":   "Long",
            "decimal":   "BigDecimal",
            "float":     "Double",
            "timestamp": "Instant (java.time)",
            "date":      "LocalDate",
            "time":      "LocalTime",
            "duration":  "Duration (java.time)",
            "uuid":      "java.util.UUID",
            "binary":    "Array[Byte]",
            "enum":      "sealed trait Name; case object A extends Name",
            "array":     "List[T] / Seq[T]",
            "object":    "Map[String, Any]",
            "map":       "Map[K, V]",
            "reference": "CaseClassName",
        },
    ),

    "ruby": ArtifactFormat(
        id="ruby",
        name="Ruby",
        category="typed_language",
        file_extension=".rb",
        description="Ruby Struct / Dry::Struct / ActiveRecord attribute definitions.",
        type_map={
            "string":    "String",
            "boolean":   "TrueClass | FalseClass",
            "integer":   "Integer",
            "decimal":   "BigDecimal (bigdecimal gem)",
            "float":     "Float",
            "timestamp": "Time / DateTime",
            "date":      "Date",
            "time":      "Time",
            "duration":  "ActiveSupport::Duration / Integer (seconds)",
            "uuid":      "String",
            "binary":    "String (encoding: BINARY / ASCII-8BIT)",
            "enum":      "Symbol (or string with validation)",
            "array":     "Array",
            "object":    "Hash",
            "map":       "Hash",
            "reference": "ClassName",
        },
    ),

    "php": ArtifactFormat(
        id="php",
        name="PHP",
        category="typed_language",
        file_extension=".php",
        description="PHP 8.1+ typed property class / readonly class definitions.",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "int",
            "decimal":   "string (bcmath) or float",
            "float":     "float",
            "timestamp": "\\DateTimeImmutable",
            "date":      "\\DateTimeImmutable",
            "time":      "\\DateTimeImmutable",
            "duration":  "\\DateInterval",
            "uuid":      "string",
            "binary":    "string",
            "enum":      "enum Name: string { case A = 'a'; }",
            "array":     "array / array<T>",
            "object":    "array|object (assoc array or stdClass)",
            "map":       "array<K, V>",
            "reference": "ClassName",
        },
        notes={
            "decimal": "PHP has no native decimal type; use BCMath functions with string representation.",
        },
    ),

    "dart": ArtifactFormat(
        id="dart",
        name="Dart / Flutter",
        category="typed_language",
        file_extension=".dart",
        description="Dart class definitions with json_serializable / freezed annotations.",
        type_map={
            "string":    "String",
            "boolean":   "bool",
            "integer":   "int",
            "decimal":   "double (or Decimal from decimal package)",
            "float":     "double",
            "timestamp": "DateTime",
            "date":      "DateTime",
            "time":      "TimeOfDay (Flutter) / DateTime",
            "duration":  "Duration",
            "uuid":      "String",
            "binary":    "Uint8List (dart:typed_data)",
            "enum":      "enum Name { a, b }",
            "array":     "List<T>",
            "object":    "Map<String, dynamic>",
            "map":       "Map<K, V>",
            "reference": "ClassName",
        },
        notes={
            "decimal": "Dart double has 64-bit IEEE 754 precision; use the `decimal` package for financials.",
        },
    ),

    "elixir": ArtifactFormat(
        id="elixir",
        name="Elixir",
        category="typed_language",
        file_extension=".ex",
        description="Elixir Ecto schema / embedded_schema + @type spec definitions.",
        type_map={
            "string":    "String.t() / :string",
            "boolean":   "boolean() / :boolean",
            "integer":   "integer() / :integer",
            "decimal":   "Decimal.t() (decimal library) / :decimal",
            "float":     "float() / :float",
            "timestamp": "DateTime.t() / :utc_datetime_usec",
            "date":      "Date.t() / :date",
            "time":      "Time.t() / :time",
            "duration":  "integer() (microseconds) or Duration.t() (Elixir 1.17+)",
            "uuid":      "Ecto.UUID.t() / :binary_id",
            "binary":    "binary() / :binary",
            "enum":      "atom() (Ecto.Enum) / :string with values list",
            "array":     "{:array, T}",
            "object":    "map() / :map",
            "map":       "map() / :map",
            "reference": "ModuleName.t()",
        },
    ),

    # ── Binary serialization formats ───────────────────────────────────────

    "protobuf": ArtifactFormat(
        id="protobuf",
        name="Protocol Buffers (proto3)",
        category="serialization",
        file_extension=".proto",
        description="Google Protocol Buffers proto3 message definitions.",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "int64",
            "decimal":   "string (no native type; encode as decimal string)",
            "float":     "double",
            "timestamp": "google.protobuf.Timestamp",
            "date":      "google.type.Date",
            "time":      "google.type.TimeOfDay",
            "duration":  "google.protobuf.Duration",
            "uuid":      "string",
            "binary":    "bytes",
            "enum":      "enum Name { NAME_UNSPECIFIED = 0; VALUE_A = 1; }",
            "array":     "repeated T",
            "object":    "google.protobuf.Struct",
            "map":       "map<string, V>",
            "reference": "MessageName",
        },
        notes={
            "decimal": "Proto3 has no decimal type. Encode as string or define a custom Amount message with int units + scale.",
            "enum":    "Proto3 enums must start with value 0 (UNSPECIFIED convention).",
        },
    ),

    "avro": ArtifactFormat(
        id="avro",
        name="Apache Avro",
        category="serialization",
        file_extension=".avsc",
        description="Apache Avro schema (JSON-based) for compact binary serialization.",
        type_map={
            "string":    "string",
            "boolean":   "boolean",
            "integer":   "long",
            "decimal":   "bytes (logicalType: decimal, precision/scale attrs)",
            "float":     "double",
            "timestamp": "long (logicalType: timestamp-millis)",
            "date":      "int (logicalType: date)",
            "time":      "int (logicalType: time-millis)",
            "duration":  "fixed (logicalType: duration, size: 12)",
            "uuid":      "string (logicalType: uuid)",
            "binary":    "bytes",
            "enum":      'enum: {"type": "enum", "symbols": [...]}',
            "array":     '{"type": "array", "items": T}',
            "object":    '{"type": "record", "fields": [...]}',
            "map":       '{"type": "map", "values": V}',
            "reference": '"RecordName"',
        },
        notes={
            "duration": "Avro duration is a 12-byte fixed with 3 unsigned 4-byte ints: months, days, milliseconds.",
        },
    ),

    "thrift": ArtifactFormat(
        id="thrift",
        name="Apache Thrift",
        category="serialization",
        file_extension=".thrift",
        description="Apache Thrift IDL struct definitions for cross-language RPC.",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "i64",
            "decimal":   "double (no native decimal; encode as string for precision)",
            "float":     "double",
            "timestamp": "i64 (epoch milliseconds)",
            "date":      "string (ISO 8601) or i32 (epoch days)",
            "time":      "i32 (seconds since midnight)",
            "duration":  "i64 (milliseconds)",
            "uuid":      "string",
            "binary":    "binary",
            "enum":      "enum Name { A = 1, B = 2 }",
            "array":     "list<T>",
            "object":    "map<string, string> (generic) or struct",
            "map":       "map<K, V>",
            "reference": "StructName",
        },
        notes={
            "decimal": "Thrift has no decimal type. Use string with explicit encoding convention or double (lossy).",
        },
    ),

    "flatbuffers": ArtifactFormat(
        id="flatbuffers",
        name="FlatBuffers",
        category="serialization",
        file_extension=".fbs",
        description="Google FlatBuffers schema for zero-copy binary serialization.",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "int64",
            "decimal":   "float64 (no native decimal)",
            "float":     "float64",
            "timestamp": "int64 (epoch milliseconds)",
            "date":      "int32 (epoch days)",
            "time":      "int32 (seconds since midnight)",
            "duration":  "int64 (milliseconds)",
            "uuid":      "string or [ubyte] (16 bytes)",
            "binary":    "[ubyte]",
            "enum":      "enum Name: int8 { A = 0, B = 1 }",
            "array":     "[T] (vector)",
            "object":    "table Name { ... }",
            "map":       "[KeyValue] (manual; no native map type)",
            "reference": "table Name",
        },
        notes={
            "map": "FlatBuffers has no native map; use a vector of key-value pair tables.",
        },
    ),

    "capnproto": ArtifactFormat(
        id="capnproto",
        name="Cap'n Proto",
        category="serialization",
        file_extension=".capnp",
        description="Cap'n Proto schema for near-zero-cost encoding.",
        type_map={
            "string":    "Text",
            "boolean":   "Bool",
            "integer":   "Int64",
            "decimal":   "Float64 (no native decimal)",
            "float":     "Float64",
            "timestamp": "Int64 (epoch nanoseconds)",
            "date":      "Int32 (epoch days)",
            "time":      "Int32 (seconds since midnight)",
            "duration":  "Int64 (nanoseconds)",
            "uuid":      "Data (16 bytes) or Text",
            "binary":    "Data",
            "enum":      "enum Name { a @0; b @1; }",
            "array":     "List(T)",
            "object":    "AnyPointer (or typed struct)",
            "map":       "List(Entry(K, V)) (manual)",
            "reference": "struct Name",
        },
        notes={
            "map": "Cap'n Proto has no built-in map. Use List of key-value struct pairs.",
        },
    ),

    "msgpack_schema": ArtifactFormat(
        id="msgpack_schema",
        name="MessagePack (schema)",
        category="serialization",
        file_extension=".yaml",
        description="MessagePack logical schema (documentation-only; types map to MessagePack format families).",
        type_map={
            "string":    "str (fixstr / str8 / str16 / str32)",
            "boolean":   "bool (true / false)",
            "integer":   "int64 (int8..int64 range detected at encode)",
            "decimal":   "ext type or str (no native decimal)",
            "float":     "float64",
            "timestamp": "ext -1 (Timestamp extension type)",
            "date":      "str (ISO 8601) or int32 (epoch days via ext)",
            "time":      "str (HH:MM:SS) or ext",
            "duration":  "int64 (milliseconds) or ext",
            "uuid":      "str or bin (16 bytes)",
            "binary":    "bin (bin8 / bin16 / bin32)",
            "enum":      "str (string values) or int (integer codes)",
            "array":     "array (fixarray / array16 / array32)",
            "object":    "map (fixmap / map16 / map32)",
            "map":       "map (fixmap / map16 / map32)",
            "reference": "(struct name — resolved at runtime)",
        },
    ),

    # ── SQL DDL formats ────────────────────────────────────────────────────

    "sql_postgresql": ArtifactFormat(
        id="sql_postgresql",
        name="SQL — PostgreSQL",
        category="sql_ddl",
        file_extension=".sql",
        description="PostgreSQL DDL (CREATE TABLE) column type mappings.",
        type_map={
            "string":    "TEXT / VARCHAR(n)",
            "boolean":   "BOOLEAN",
            "integer":   "BIGINT",
            "decimal":   "NUMERIC(precision, scale)",
            "float":     "DOUBLE PRECISION",
            "timestamp": "TIMESTAMPTZ",
            "date":      "DATE",
            "time":      "TIMETZ",
            "duration":  "INTERVAL",
            "uuid":      "UUID",
            "binary":    "BYTEA",
            "enum":      "VARCHAR(n) + CHECK (...) or custom TYPE",
            "array":     "JSONB or native ARRAY type (T[])",
            "object":    "JSONB",
            "map":       "JSONB",
            "reference": "UUID (+ FOREIGN KEY constraint)",
        },
    ),

    "sql_mysql": ArtifactFormat(
        id="sql_mysql",
        name="SQL — MySQL / MariaDB",
        category="sql_ddl",
        file_extension=".sql",
        description="MySQL 8+ / MariaDB DDL column type mappings.",
        type_map={
            "string":    "TEXT / VARCHAR(255)",
            "boolean":   "TINYINT(1) / BOOLEAN",
            "integer":   "BIGINT",
            "decimal":   "DECIMAL(precision, scale)",
            "float":     "DOUBLE",
            "timestamp": "DATETIME(6) / TIMESTAMP",
            "date":      "DATE",
            "time":      "TIME",
            "duration":  "BIGINT (milliseconds)",
            "uuid":      "CHAR(36) or BINARY(16)",
            "binary":    "BLOB / LONGBLOB",
            "enum":      "ENUM('a', 'b') or VARCHAR + CHECK",
            "array":     "JSON",
            "object":    "JSON",
            "map":       "JSON",
            "reference": "BIGINT / CHAR(36) (+ FOREIGN KEY constraint)",
        },
    ),

    "sql_clickhouse": ArtifactFormat(
        id="sql_clickhouse",
        name="SQL — ClickHouse",
        category="sql_ddl",
        file_extension=".sql",
        description="ClickHouse DDL column type mappings (MergeTree engine family).",
        type_map={
            "string":    "String",
            "boolean":   "Bool / UInt8",
            "integer":   "Int64",
            "decimal":   "Decimal(precision, scale)",
            "float":     "Float64",
            "timestamp": "DateTime64(3, 'UTC')",
            "date":      "Date / Date32",
            "time":      "String (no native TIME; store as HH:MM:SS string)",
            "duration":  "Int64 (milliseconds)",
            "uuid":      "UUID",
            "binary":    "String (store as hex or base64)",
            "enum":      "Enum8('a'=1, 'b'=2) or Enum16",
            "array":     "Array(T)",
            "object":    "JSON (experimental) / String",
            "map":       "Map(K, V)",
            "reference": "String / UUID (no FK enforcement)",
        },
        notes={
            "time":   "ClickHouse has no TIME type; use String (HH:MM:SS) or seconds-since-midnight Int32.",
            "object": "ClickHouse JSON type is experimental; prefer String with JSON encoding or nested columns.",
        },
    ),

    "sql_snowflake": ArtifactFormat(
        id="sql_snowflake",
        name="SQL — Snowflake",
        category="sql_ddl",
        file_extension=".sql",
        description="Snowflake DDL column type mappings.",
        type_map={
            "string":    "VARCHAR / TEXT",
            "boolean":   "BOOLEAN",
            "integer":   "NUMBER(18, 0) / BIGINT",
            "decimal":   "NUMBER(precision, scale)",
            "float":     "FLOAT / DOUBLE",
            "timestamp": "TIMESTAMP_TZ",
            "date":      "DATE",
            "time":      "TIME",
            "duration":  "NUMBER (milliseconds)",
            "uuid":      "VARCHAR(36)",
            "binary":    "BINARY",
            "enum":      "VARCHAR (FK not enforced; use CHECK constraint)",
            "array":     "ARRAY",
            "object":    "OBJECT / VARIANT",
            "map":       "OBJECT",
            "reference": "VARCHAR (FK not enforced in Snowflake)",
        },
    ),

    "sql_bigquery": ArtifactFormat(
        id="sql_bigquery",
        name="SQL — BigQuery",
        category="sql_ddl",
        file_extension=".sql",
        description="Google BigQuery DDL column type mappings (Standard SQL).",
        type_map={
            "string":    "STRING",
            "boolean":   "BOOL",
            "integer":   "INT64",
            "decimal":   "NUMERIC / BIGNUMERIC",
            "float":     "FLOAT64",
            "timestamp": "TIMESTAMP",
            "date":      "DATE",
            "time":      "TIME",
            "duration":  "INT64 (microseconds)",
            "uuid":      "STRING",
            "binary":    "BYTES",
            "enum":      "STRING (validate with CHECK or downstream logic)",
            "array":     "ARRAY<T>",
            "object":    "STRUCT<field T, ...>",
            "map":       "ARRAY<STRUCT<key STRING, value T>> (no native map)",
            "reference": "STRING (no FK enforcement in BQ)",
        },
        notes={
            "map": "BigQuery has no native map type. Use ARRAY<STRUCT<key, value>> or JSON STRING.",
        },
    ),

    "sql_sqlite": ArtifactFormat(
        id="sql_sqlite",
        name="SQL — SQLite",
        category="sql_ddl",
        file_extension=".sql",
        description="SQLite DDL column type mappings (dynamic type affinity system).",
        type_map={
            "string":    "TEXT",
            "boolean":   "INTEGER (0 or 1)",
            "integer":   "INTEGER",
            "decimal":   "NUMERIC / TEXT (store as string for precision)",
            "float":     "REAL",
            "timestamp": "TEXT (ISO 8601) or INTEGER (epoch seconds)",
            "date":      "TEXT (YYYY-MM-DD)",
            "time":      "TEXT (HH:MM:SS)",
            "duration":  "INTEGER (milliseconds)",
            "uuid":      "TEXT",
            "binary":    "BLOB",
            "enum":      "TEXT (validate at application layer)",
            "array":     "TEXT (JSON)",
            "object":    "TEXT (JSON)",
            "map":       "TEXT (JSON)",
            "reference": "INTEGER / TEXT (FK via FOREIGN KEY clause)",
        },
        notes={
            "boolean": "SQLite stores booleans as INTEGER 0/1; no native BOOLEAN type.",
            "decimal": "Use TEXT and BCMath-style arithmetic to avoid IEEE 754 rounding.",
        },
    ),

    # ── Data tool / infrastructure formats ─────────────────────────────────

    "dbt": ArtifactFormat(
        id="dbt",
        name="dbt (schema.yml)",
        category="data_tool",
        file_extension=".yml",
        description="dbt schema.yml column descriptions + tests (actual SQL types depend on the underlying warehouse).",
        type_map={
            "string":    "text / varchar (warehouse-dependent)",
            "boolean":   "boolean",
            "integer":   "bigint / int64",
            "decimal":   "numeric / decimal",
            "float":     "float / float64 / double",
            "timestamp": "timestamp / timestamptz",
            "date":      "date",
            "time":      "time",
            "duration":  "bigint (milliseconds)",
            "uuid":      "varchar(36) / string",
            "binary":    "bytes / blob",
            "enum":      "varchar + accepted_values test",
            "array":     "array (warehouse-dependent) or json",
            "object":    "json / jsonb / variant",
            "map":       "json / jsonb / variant",
            "reference": "varchar / uuid (+ relationships test)",
        },
        notes={
            "enum":      "Use dbt `accepted_values` data test to enforce enum constraints.",
            "reference": "Use dbt `relationships` data test to enforce referential integrity.",
        },
    ),

    "terraform": ArtifactFormat(
        id="terraform",
        name="Terraform (HCL schema)",
        category="data_tool",
        file_extension=".tf",
        description="Terraform HCL resource schema type mappings (for custom providers or variable definitions).",
        type_map={
            "string":    "string",
            "boolean":   "bool",
            "integer":   "number",
            "decimal":   "number",
            "float":     "number",
            "timestamp": "string (RFC 3339)",
            "date":      "string (YYYY-MM-DD)",
            "time":      "string (HH:MM:SS)",
            "duration":  "string (Go duration) or number (seconds)",
            "uuid":      "string",
            "binary":    "string (base64-encoded)",
            "enum":      "string (+ validation block)",
            "array":     "list(T) or set(T)",
            "object":    "map(T) or object({attr = type, ...})",
            "map":       "map(T)",
            "reference": "string (computed / data source reference)",
        },
        notes={
            "decimal": "Terraform number is a 64-bit float; avoid for high-precision financial values.",
        },
    ),

    "markdown_docs": ArtifactFormat(
        id="markdown_docs",
        name="Markdown Documentation",
        category="data_tool",
        file_extension=".md",
        description="Human-readable Markdown data dictionary generated from model/projection definitions.",
        type_map={
            "string":    "Text string",
            "boolean":   "Boolean (true / false)",
            "integer":   "64-bit integer",
            "decimal":   "Fixed-precision decimal number",
            "float":     "64-bit floating-point number",
            "timestamp": "ISO 8601 datetime with timezone",
            "date":      "Calendar date (YYYY-MM-DD)",
            "time":      "Time of day (HH:MM:SS)",
            "duration":  "ISO 8601 duration (e.g. PT1H30M)",
            "uuid":      "UUID v4 string (RFC 4122)",
            "binary":    "Raw binary / base64-encoded bytes",
            "enum":      "Enumerated string value",
            "array":     "Ordered list of items",
            "object":    "Nested key-value object",
            "map":       "Dynamic key-value map",
            "reference": "Reference to another model entity",
        },
    ),
}

# ---------------------------------------------------------------------------
# Category metadata
# ---------------------------------------------------------------------------

CATEGORY_LABELS: dict[ArtifactCategory, str] = {
    "api_spec":       "API Specification",
    "typed_language": "Typed Programming Language",
    "serialization":  "Binary Serialization",
    "sql_ddl":        "SQL / DDL",
    "data_tool":      "Data Tool / Infrastructure",
}

CATEGORY_ORDER: list[ArtifactCategory] = [
    "api_spec", "typed_language", "serialization", "sql_ddl", "data_tool",
]

# ---------------------------------------------------------------------------
# Helper functions
# ---------------------------------------------------------------------------


def get_format(format_id: str) -> ArtifactFormat | None:
    """Return the ArtifactFormat for *format_id*, or None if unknown."""
    return ARTIFACT_FORMATS.get(format_id)


def list_formats(category: ArtifactCategory | None = None) -> list[ArtifactFormat]:
    """Return all formats, optionally filtered by category, in canonical order."""
    formats = list(ARTIFACT_FORMATS.values())
    if category:
        formats = [f for f in formats if f.category == category]
    return formats


def formats_by_category() -> dict[ArtifactCategory, list[ArtifactFormat]]:
    """Return formats grouped by category, in CATEGORY_ORDER order."""
    result: dict[ArtifactCategory, list[ArtifactFormat]] = {c: [] for c in CATEGORY_ORDER}
    for fmt in ARTIFACT_FORMATS.values():
        result[fmt.category].append(fmt)
    return result


VALID_ARTIFACT_FORMAT_IDS: frozenset[str] = frozenset(ARTIFACT_FORMATS.keys())
